### ISSUE TITLE
Is it possible to display shields like the default blizzard UI does?

### ISSUE THREAD

**Issue by TheInternetIsReal** [michaelnpsp/Grid2#1]
I have the same ask as this user: https://www.reddit.com/r/WowUI/comments/jct6ts/help_grid2_display_shield_and_overflow_shield/

Is it possible to get the shield bar to line up exactly at where the player's current health is? Instead of always anchoring on the right or left side of the bar like so:
![image](https://user-images.githubusercontent.com/8439537/103432532-1cc7d280-4b95-11eb-9ea9-71197f575d39.png)

**Comment by michaelnpsp** [comment]
Yes , You must use a multibar indicator. This guide:
https://web.archive.org/web/20200128114353/http://murlocparliament.com/how-2-grid2/
explains howto setup several bars in a multibar indicator to display health+shields+healing incoming etc.
