### ISSUE TITLE
Hide duplicate (de)buffs in statuses

### ISSUE THREAD

**Issue by Snakybo** [michaelnpsp/Grid2#10]
Hi! I'm re-arranging my setup a bit, and have added an indicator for `icons` to show debuffs, that works perfect. However I also added all the various debuff statuses (Curse, Disease, Magic, Poison) to that indicator as that also captures dispellable debuffs that aren't caught by the Raid Debuffs status.

What I'm experiencing now is duplicate icons for dispellable debuffs that are _also_ caught by the Raid Debuffs status, example below:
![image](https://user-images.githubusercontent.com/3172140/107163396-8a8fc700-69a9-11eb-86bd-1cf354d20ddb.png)

Is it possible to add a filter to hide a (de)buff if the aura is already visualized within the indicator? I know you can blacklist debuff or disable them within Raid Debuffs, but that's a bit too tedious to maintain for my liking, so a feature for this would be much appreciated :)

Thanks :)

**Comment by michaelnpsp** [comment]
Very difficult to implement, statuses are independent they don't know about another statuses. 
1.  You can create/use a "Debuffs Group" status (this status can display all debuffs event the curse/disease/magic/poison debuffs) and blacklist debuffs you dont want to see.
2. Or you can add a missing curse/disease/magic/poison debuffs to the Raid Debuffs list.
