### ISSUE TITLE
Was the test mode removed? (WOTLK Classic)

### ISSUE THREAD

**Issue by rileylyman** [michaelnpsp/Grid2#100]
I am unable to find the test mode that many guides talk about when configuring Grid2. A mode where 25 unit frames are added so I can test out my layout. Was this mode removed?

**Comment by michaelnpsp** [comment]
1. Goto general/layouts/by group type tab.
2. Select a layout for solo/arena/party or raid 
3. Click on the magnifying glass icon to the right of the layout name to test the selected layout.
