### ISSUE TITLE
[Bug] Some Blizz frames are still visible

### ISSUE THREAD

**Issue by yoh-m** [michaelnpsp/Grid2#105]
Hi there!

Just having a weird problem since the start of Dragonflight : I have some weird "default UI" that are appearing (not even the new Blizz UI) in arena : [https://imgur.com/a/vhJRoCz](https://imgur.com/a/vhJRoCz)

I have checked both options in "Blizzard Raid Frames", and they only disappear when I uncheck, check them again then reload UI (tried to only reload UI, doesn't work).

**Comment by yoh-m** [comment]
Here is the fstack : [https://imgur.com/a/CT8vi8S](https://imgur.com/a/CT8vi8S)

My guess would be some ArenaEnemyPrepFramesContainer coming from [ArenaUI.xml](https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/ArenaUI.xml) but I'm not so sure

**Comment by michaelnpsp** [comment]
Grid2 does not try to hide arena stuff. only blizzard raid and party friendly frames
