### ISSUE TITLE
No option to hide player in raid or give dedicated position in frames

### ISSUE THREAD

**Issue by vurstp** [michaelnpsp/Grid2#107]
Is there anyway to hide the player frame in raid? - I know this is possible with partys. 
Is there a way to give the player a dedicated spot in the layout? - for example, always first/last.

Thank you for your time and hard work!

**Comment by michaelnpsp** [comment]
Not possible.

**Comment by vurstp** [comment]
But you can populate frames with just names alone. There isn't a way to exclude someone by name?

Oh btw, a work around I found is unchecking "No Role" in the layout editor, and then setting whoever you want to exclude with no role. It works, but is obviously confusing in pugs.

**Comment by michaelnpsp** [comment]
Grid2 uses blizzard code to  create and display the frames, in the link  below you can see  the "rules/templates" allowed by the blizzard code to rearrange and display the frames and there is no attribute to configure player visiblity while in raid.

https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/SecureGroupHeaders.lua

It is possible to define a list of players , but this list cannot be changed in combat, so the layout cannot be reconfigured when a player joins or leaves the raid while in combat. The result is a lot of issues of people claiming the layout does not work. So the base Grid2 code does not include this kind of "dynamic" layouts (there is an  undocumented excepcion  that maybe i will remove in the future)
