### ISSUE TITLE
Health without the "%" and health that include shield? 

### ISSUE THREAD

**Issue by Unmoist** [michaelnpsp/Grid2#109]
Is there a chance for getting health-current without the % so it's 100 instead of 100%
and getting the health to go up if a player have a shield for 20% of the health it's 120% health instead of just 100 with a shield. 
And

**Comment by michaelnpsp** [comment]
I added an "Add shield" option to health-current status in 2.2.5-beta version, but the percent cannot be removed sorry.

**Comment by Unmoist** [comment]
What is the reason it can't be removed? 
Grid2 codewise or?

**Comment by Unmoist** [comment]
Well you said it! :D
