### ISSUE TITLE
Overshield mutilbar texture

### ISSUE THREAD

**Issue by Unmoist** [michaelnpsp/Grid2#110]
Multibar texture is rotating or something when using textures see picture. 
![image](https://user-images.githubusercontent.com/125043011/220363294-9eedabb3-f68a-4a73-b1c6-5ea88a7b2063.png)
Should look like this: 
![image](https://user-images.githubusercontent.com/125043011/220363450-9488669c-0651-4fd9-87e0-a9cb66e9c4c8.png)

Is this a bug or something?

**Comment by michaelnpsp** [comment]
Bar Textures are stretched not tiled and there is no configuration option to change this behaviour.

**Comment by Unmoist** [comment]
Ah okay, but it only happens when I use multibar.

**Comment by michaelnpsp** [comment]
Try out 2.2.6-beta version.
I added some texture options for bars to enable texture tiling and adjust the texture to maintain the aspect ratio.
Depending of the texture you are using, maybe enabling the "Horizontal Tiles" option you can get the desired behavior for the texture.

**Comment by Unmoist** [comment]
that was so much better, and works like a charm! 
(and so pretty with each bar has a tab!)
