### ISSUE TITLE
Is it possible to mimic the function irrelevant if more from Vuhdo in Grid2?

### ISSUE THREAD

**Issue by DamienShahan** [michaelnpsp/Grid2#115]
In Vuhdo there is a function called "irrelevant if more" that lets your define a specific color, if the player has more than the entered amount of life.

![image](https://user-images.githubusercontent.com/22813288/222806217-84098006-63db-4c36-bfd9-c8f1e074c700.png)

In Grid2 I can't find a similar option und way to mimic the function. In Grid2 you can define the gradient colors, but I don't see how to add a 4th color for players at max life.

![image](https://user-images.githubusercontent.com/22813288/222806273-4730d313-4cae-4d31-a6b6-4e2a9c061c7f.png)

If I set "Full Health" to dark green, then the gradient between green and yellow is pretty dark.
On the right side you can see the same effect in vuhdo, but I want to use grid2 for next tier.

![image](https://user-images.githubusercontent.com/22813288/222806307-8afe51d3-2d6a-408e-a3ec-37d381b58a7f.png)

**Comment by DamienShahan** [comment]
I also tried the health deficit status, but as far as I can see, that color triggers when I am below a certain threshold. But I am looking for a function that triggers only above a certain threshold.

![image](https://user-images.githubusercontent.com/22813288/222806831-c73fba89-1042-448a-bce0-3cffd6a11def.png)
![image](https://user-images.githubusercontent.com/22813288/222806843-130eba7f-752a-4e0a-8caf-579526586c4a.png)

**Comment by michaelnpsp** [comment]
You can use health-deficit or health low, and link the status  to the bar colors indicator tab with a higher priority.
For example if your bar colors tab has:
health-low
health-current

health-current color will be used when the player is at full health, and health-low when not.

**Comment by DamienShahan** [comment]
I am sorry for being unclear in my post. I want to keep the smooth color gradient from health-current, however use it for 0%-99% life. Then at 100% have a different color set, like color:darkgreen.

Setting health-low then health-current, means players only have 1 single color when less than full health (since health-low can only have 1 color).
![image](https://user-images.githubusercontent.com/22813288/222905763-ca0c83af-e918-4f93-8cbb-47565aaca4aa.png)
![image](https://user-images.githubusercontent.com/22813288/222905772-22152cc6-f720-4d32-ac58-e672bc0b1023.png)


Like this, the color does a hard jump from one color to the next at the life % thresholds. 
![image](https://user-images.githubusercontent.com/22813288/222905581-1be081de-f89e-468a-a958-a7c0876f5683.png)

**Comment by michaelnpsp** [comment]
Try out 2.2.8-beta version, I added a invert status option to HealthLow status.

**Comment by DamienShahan** [comment]
Omg, it is perfect. Thank you so much. <3
Do you have a donation or paypal friends link?

**Comment by michaelnpsp** [comment]
Only the donate button in curseforge:
https://www.curseforge.com/wow/addons/grid2

**Comment by DamienShahan** [comment]
Thanks for your super fast support and even adding the feature. I wasn't expecting that at all. I sent you a donation. :)

**Comment by michaelnpsp** [comment]
Thanks for your support.
