### ISSUE TITLE
Multibar: "health-current" not using correct colors?

### ISSUE THREAD

**Issue by jmctune** [michaelnpsp/Grid2#116]
## Versions
**Grid Version**: Grid 2.1.3
**WoW Version**: Retail (DF)

## Issue

Hey there,

Thanks for maintaining this add-on! Never play without it.

The out of the box "health-current" status changes the color of your health bar based on the amount of health you have left. This works great when it's just used as a bar. As a multibar, you only have the choice to set a "Status Color" or "Custom Color". Using "Status Color" doesn't honor the color configuration in the status's configuration screen.

Is it possible to have the regular bar and multibar operate the same way in regards to changing its color based on the remainder of health left?

Thanks!

**Comment by michaelnpsp** [comment]
multibar works like the standard bars for mainbar color, there if not difference. If you dont get the same results, then your settings are different configured in the multibar.  Select "Status Color" and add the desired color statuses in the Colors Tab.

**Comment by jmctune** [comment]
You're totally right. I was looking at the color configuration in the bars tab and not in the colors tab. Sorry to waste your time!
