### ISSUE TITLE
[Question] add shields to health percent

### ISSUE THREAD

**Issue by mollad** [michaelnpsp/Grid2#117]
Regarding "Added an option to health-current status to add shields to health percent (github issue #109)"

Is this just for retail, Or am i missing something where in Grid2 Wrath am i suppose to find this?

Dont have anything under health-current.

**Comment by michaelnpsp** [comment]
Only for retail because Blizzard disabled the shields api for classic. so there are no shields status available in Wrath.

**Comment by mollad** [comment]
Ok thanks :(
