### ISSUE TITLE
Rangecheck on monk doesn't work whenever you're not specced into Detox

### ISSUE THREAD

**Issue by Reloe** [michaelnpsp/Grid2#118]
Not sure when this broke but it wasn't the case for all of Dragonflight.
Basically rangecheck is using Detox and if you don't have that talented it'll return false for every unit.
I suggest changing it to Vivify (116670)
StatusRange.lua line 49

**Comment by michaelnpsp** [comment]
Try out version 2.2.11-beta

**Comment by Reloe** [comment]
Yep that works, thanks
