### ISSUE TITLE
[Request] Allow to mouselook through frames with right click

### ISSUE THREAD

**Issue by lordblackadder** [michaelnpsp/Grid2#119]
For people who do not use right click menu, it would be nice to have the option to mouselook through the frames. As long as it only affects right mouse button it shouldn't change the targeting behaviour either. Would that be possible?

**Comment by michaelnpsp** [comment]
Install Clique addon. Enable "Trigger bindings on the 'down' portion of the click" on Clique configuration. Create this custom macro line for Right Mouse button:

/run MouselookStart()

**Comment by lordblackadder** [comment]
Thanks, will do that and close this.
