### ISSUE TITLE
TBC Beta Update?

### ISSUE THREAD

**Issue by jlanier03** [michaelnpsp/Grid2#12]
With TBC Beta addons now enabled are there plans to release a TBC Beta grid2?

**Comment by michaelnpsp** [comment]
No plans, i have no access to the beta version, so its not possible for me to test or fix anything.

**Comment by michaelnpsp** [comment]
You can try out 2.0.4-alpha-classic version
https://www.wowace.com/projects/grid2/files/3260953
Important, Due to a blizzard bug you must uncheck the "Layouts/General tab/Use Blizzard UnitFrames" option (and then Reload the UI).
Report any crash, i cannot test the changes.
