### ISSUE TITLE
Reloading moves frames when uiscale is changing

### ISSUE THREAD

**Issue by holypalaswe** [michaelnpsp/Grid2#122]
I use a weakaura to set uiscale to 0.53333 everytime I login since it's below the default minimum by blizzard.

This works fine whenever I login first time, or relog. But if I do /reload the frames are being moved.
This is easily fixed by doing a /run Grid2Layout:RestorePosition() - which I have added to the weakaura to be done automatically, and fixes the problem for the main raidframe.

The problem that remains is that the pet-frames that are detached from the main raidframe are not updated with Grid2Layout:RestorePosition() so they don't get fixed. This requires either a relog to fix, or setting the vertical/horizontal again: 
https://i.imgur.com/jjieOmy.mp4

**Comment by michaelnpsp** [comment]
Try out with:
`Grid2Layout:ReloadLayout(true)
`

**Comment by holypalaswe** [comment]
> 

Sick! That works!

**Comment by holypalaswe** [comment]
> Try out with: `Grid2Layout:ReloadLayout(true) `

Sick! That works!
