### ISSUE TITLE
[Request] Text Alignment

### ISSUE THREAD

**Issue by Kolmarwow** [michaelnpsp/Grid2#126]
Request to add text alignment for text indicator modules so that you can specify if text formatting should be aligned left, center or right (currently defaults to center and cannot be changed afaik).

**Comment by michaelnpsp** [comment]
You can align to left or right changing the text location or align point. 
But there is a bug in the configuration options and sometimes the UI must be reloaded to apply the new settings.

**Comment by Kolmarwow** [comment]
Ah I see, thank you.
