### ISSUE TITLE
Add important PVP Debuffs

### ISSUE THREAD

**Issue by stevebeck89** [michaelnpsp/Grid2#13]
A fellow healer in my RBG team uses this addon and does not see important PVP debuffs such as stuns and other cc that needs to be dispelled.

Please consider adding a list of pvp debuffs.  Maybe this could be another RaidDebuffs group.

**Comment by michaelnpsp** [comment]
It seems the profile used by your friend is not configured to display all debuffs.
You friend can create a "Debuffs Group" status and link this status to any icon or icons indicator to display all debuffs or a debuffs subset (Different filters can be configured in the status configuration).

**Comment by stevebeck89** [comment]
Thank you for the help! It does look like the ability to configure these debuffs is available but it certainly requires more effort than adding the current raid debuffs.

It does seem like a one person creating a list of important pvp debuffs and sharing it could still be helpful. I personally use BigDebuffs as this gives an out of the box priority of pvp debuffs to start with.  Without the ability to at least share debuff list between players I can't recommend this add-on for pvp.

Good job on the add-on though this works well for raids especially when setup!
