### ISSUE TITLE
Glow line after shield. 

### ISSUE THREAD

**Issue by Unmoist** [michaelnpsp/Grid2#130]
Hello, 
Is it possible to get like a glowborder after the over shield and shield like on the picture? 
![image](https://user-images.githubusercontent.com/125043011/236737047-479d0d34-9db7-4812-8606-849e3ca4a180.png)

**Comment by michaelnpsp** [comment]
Can you explain your multibar setup ? 
I dont undertand how is posible to put something after the shields: after displaying a overshield+shield bars, there is no remaining room  to display more bars in the multibar, because  overshield+shield  amount is a value higher than the maximun unit health.

**Comment by Unmoist** [comment]
The picture is taken from using overshield addon on blizzard frames. 
I just like there is like an end to the shield multi bar. 
That's why I'm asking if it's possible to make so there is a glow at the end.

**Comment by Unmoist** [comment]
So you can't anchor it to the shield overflow so it follows the bar? 
Atm It only stays where you put the location point.

**Comment by michaelnpsp** [comment]
No, you can't
