### ISSUE TITLE
Is it possible to split melee dps and ranged dps when sorting players by their roles?

### ISSUE THREAD

**Issue by DamienShahan** [michaelnpsp/Grid2#131]
Hello

I am trying to pre-set the order of the roles in my raid frames. 

Currently I have the players ordered by Tank -> DPS -> Healer as shown in this picture:
![image](https://github.com/michaelnpsp/Grid2/assets/22813288/e208c80d-da73-4b14-b1a2-8cb4ef0ae120)

There is even a fourth dropdown selector there, but only none as a fourth option:
![image](https://github.com/michaelnpsp/Grid2/assets/22813288/fadeb256-9983-444e-a1a5-6177f3e31465)

Is there a way to set the order to Tank -> Melee DPS -> Range DPS -> Healer that I am just missing?

Cheers

**Comment by michaelnpsp** [comment]
Not possible,  there is no such option.
