### ISSUE TITLE
Is it possible to filter all "Raid Debuffs" in other debuff types?

### ISSUE THREAD

**Issue by DamienShahan** [michaelnpsp/Grid2#132]
I currently have both Raid Debuffs and Typeless debuffs visible in my indicator, so that I also see important typless debuffs in other content (like m+).

Is it possible to blacklist/filter all Raid Debuffs in the other Debuff types, without having to add each single one to the filter list?

Here is an example of how I tried to filter the entire raid debuff list from my Poison Type, since Typeless has a bunch of other blacklisted stuff as well. But this does not work.
![image](https://github.com/michaelnpsp/Grid2/assets/22813288/7057704a-09a1-480a-b31f-2b92ed477ab7)

Since I have both typeless and raid debuffs active, all enabled raid debuffs are shown twice on my frames:
![image](https://github.com/michaelnpsp/Grid2/assets/22813288/4ddb243d-edcb-47e2-9381-e0102443023b)

Cheers

**Comment by michaelnpsp** [comment]
You can create a Debuffs Group, this status has more filter options,:
To create a debuffs group, goto debuffs, on the right panel select "Debuffs" on "Select Type" option, type a descriptive name for the new debuffs group, click create button:
But keep in mind that "Boss Debuffs" in the status filter is not the same that "Raid Debuffs", what is a boss debuff is decided by the game, instead a raid debuff is any debuff added in the raid debuff module configuration (this can include any debuff).

![grid2-debuffs-group-example1](https://github.com/michaelnpsp/Grid2/assets/54121140/be79e93d-151b-4400-94c5-b7af2fa4fb57)

**Comment by DamienShahan** [comment]
Thank you for that tip. Using a self made filter worked:

![image](https://github.com/michaelnpsp/Grid2/assets/22813288/65541941-19cf-4d73-9bc0-97a36a20efc2)

**Comment by atremblay** [comment]
How does `Use strict filtering` works? The way I understand it is that everything that is checked must be True. But you can't have both `(Short Duration AND Long Duration)` or `(Non Boss Debuffs AND Boss Debuffs)` at the same time, they are mutually exclusive.

**Comment by michaelnpsp** [comment]
Yes its a bit confusing maybe i should  think how to display the filters in a more intuitive way. 
Be default all debuffs are displayed (all checked) and you hide things unchecking options, 
When both options in a row are checked,the filter for this row does not exists at all, so nothing to filter, nothing to hide. 

The "use strict filtering" is applied between rows. so if you want  for example:
Long duration debuffs that can be Dispelled, you uncheck "short duration" and "non dispellable".

If the "use strict filtering" is uncheked in the above example::
The addon will display the debuff even if only one condition is met:  "is long duration" or "is dispelable."

**Comment by atremblay** [comment]
Ah ok, so the rows have an OR condition while the columns will have and AND condition if 'use strict filtering'

Goes something like this (if 'use string filtering' is checked)
```
(Dispellable OR Non Dispellabel)
AND 
(Typed OR Untyped)
AND 
...
(Non self casted OR Self Casted)
```

If 'use strict filtering' is unchecked, then the AND become OR

Thanks for the clarification.

**Comment by lwalter** [comment]
Hey @michaelnpsp , thanks for your work on this addon. 

I'm also trying to achieve something similar to the original request here. My current set up is two icons indicators (one in bottom left, another in center). Then a debuffs status group (see settings below) attached to the bottom left indicator and the Raid Debuffs status on the center indicator.

![Image](https://github.com/user-attachments/assets/cf8def8a-1042-47ff-8906-165ddb9f9e33)

My desire is to have the debuffs status group exclude any debuffs shown by the Raid Debuffs status group. Is this possible with the existing configuration available?
