### ISSUE TITLE
Bug when hearthstoning out in boss combat

### ISSUE THREAD

**Issue by holypalaswe** [michaelnpsp/Grid2#133]
A very niche issue since I speedrun ulduar and one of my jobs is to pull Algalon and then HS out to reset him. 

When I do this however, Grid2 bugs out a little bit so I have to /reload.

Algalon pull -> HS -> Loading Screen -> 2-3sec after loadingscreen my combat drops (topright of my playerframe on shadowed unitframes shows when combat drops) -> Grid2 names disappear (and probably other issues not seen?).
https://www.twitch.tv/videos/1827368212?t=1h14m33s
https://www.twitch.tv/videos/1827368212?t=2h48m31s

grid2 profile: https://pastebin.com/nVwDsGtA

**Comment by michaelnpsp** [comment]
Unfortunatelly I can not replicate the exact conditions to trigger the issue, and tests in another bosses with your profile were working fine in my computer. Can you check if some lua error is happening ?

**Comment by holypalaswe** [comment]
No lua error recorded. It does fix itself even without /reloading if you have another loadingscreen. So ended up not mattering for me personally.
