### ISSUE TITLE
Feature request, beacon of light range checker.

### ISSUE THREAD

**Issue by holypalaswe** [michaelnpsp/Grid2#134]
I am currently editing the StatusRange.lua to use beacon of light (53563) as the spell used in Heal Range rangechecker. And with this I setup an indicator to use rangealt w/ heal (& range w/ 38y with 0% alpha) to have an icon show up whenever someone is >40y but <60y, making it easy to know if my beacon will reach them. 

Looks something like this https://imgur.com/3bPjF04

Just wondering if beacon of light (53563) 60y range could be added as an option in the dropdown of the range & rangealt rangecheckers.

**Comment by michaelnpsp** [comment]
The addons displays the spells available in the player spellbook, so the "Beacon of light" spell should be listed in the Range options dropdown, at least in my not max level paladin the spell is displayed in the dropdown.
