### ISSUE TITLE
[WotLK] Getting a popup that says "Couldn't load Blizzard_CUFProfiles: Disabled"

### ISSUE THREAD

**Issue by charlespierce** [michaelnpsp/Grid2#137]
Hi, as of today's patch for WotLK Classic, whenever I log in or reload UI, I'm getting a popup in the middle of my screen saying "Couldn't load Blizzard_CUFProfiles: Disabled".

This only seems to happen when I have "Hide Blizzard Raid Frames" turned on in Grid2—With that option turned off I don't see anything. I've tried searching for what the cause could be, but can't find anything that would point me towards what may be causing the issue.

**Comment by michaelnpsp** [comment]
Try out [2.3.8-wrath](https://www.wowace.com/projects/grid2/files/4600214) version.
This version should hide the blizzard raid frames with no errors.
If the option is already checked, you must uncheck and check the option.

**Comment by charlespierce** [comment]
That fixed it, thanks for the quick update!
