### ISSUE TITLE
Add support for "trivial" and "important" debuffs

### ISSUE THREAD

**Issue by Toludin** [michaelnpsp/Grid2#138]
This is a pretty big ask so I realize it might not be feasible, but since it's part of the base UI, I thought maybe it is something that could be done.

The base raid unitframes have an interesting handling of debuffs, where some debuffs (I think especially spec-dispellable ones, though that might not be everything) are seemingly labeled as "important" in some way, such that they will show up larger and temporarily obscure/block standard debuffs on a character. Here's an example of this:

Trivial debuffs on all players (including the tank): 
![image](https://github.com/michaelnpsp/Grid2/assets/236548/bab82d96-b29b-4221-8a14-7674ded142cb)

Tank is hit by a dispellable debuff, which shows up larger and temporarily blocks the other debuffs on the frame:
![image](https://github.com/michaelnpsp/Grid2/assets/236548/b37c6245-e483-4d3a-8c3a-230627e8434c)

Also, some debuffs are are labeled as "trivial" and only show up out of combat (Sated debuffs, for instance):

Same group after combat, where the Sated and Challenger debuffs now show up:
![image](https://github.com/michaelnpsp/Grid2/assets/236548/cb6b84e5-d121-4abc-a05d-456554ddcc6d)

I know we do currently have the Debuffs and DebuffsDispellable groups, and I could add a whitelisted DebuffsOOC group that only shows up out of combat, but I don't think these could all interact cohesively in one indicator, stacking together when appropriate and allowing for things like the dispellable debuffs to be larger and block showing the standard ones, etc.

Another possible option would be to allow for customized icon sizes per status, rather than having it always tied to the indicator. So I could set, say, the Debuffs icon at 24 px and the DebuffsDispellable icon at 36 px and at least get the larger dispellable icons there.

Anyway, I know this would be a pretty large endeavor so no worries if you say no. I was just watching some streams and realized there seemed to be something that was done by default by the basic frames that looked useful but that I couldn't do with Grid2. Thanks!

**Comment by Unmoist** [comment]
Ayije, where this UI is from. 
He uses a custom build bigdebuff addon, with alot of changes + his own add-on over laying. 
But this could be nice to have.
