### ISSUE TITLE
Add option to set a fixed maximum duration for buffs/debuffs

### ISSUE THREAD

**Issue by vincebeck** [michaelnpsp/Grid2#139]
Some auras (HoTs such as the Evoker's "Reversion") have mechanics by which they are "reset" or "reapplied". In the case of the Evoker's "Reversion" ability, when it crits, the duration is extended by 1 second. This results in any indicators configured in grid2 (whether sweeping icons or bars) to be reset in length, and receive a faster countdown movement, leading to them no longer being synchronous in relation to the same aura on other party frame units. I assume this is because WoW implement the +1 sec duration when "critting" as a cancellation and re-application of the ability with a new timer (current +1), probably resulting in a new log event which grid 2 picks up under the given spell ID.

A possible solution could be to add an option to apply a custom "maximum" duration or value for a given status. The bar module could pick this up and overwrite the dynamically set "full bar length value".

**Comment by michaelnpsp** [comment]
Working as intended, Grid2 simply displays the information provided by the game.
I really dont know if using a fixed value (ignoring the game duration) has sense. 
Which max duratoin is reasonable ?, if the inital reversion duration is 12 seconds , should the addon display a faked 20 seconds max duration for example ? and what to todo if finally the buff goes above 20 seconds  duration on next applications  ?

**Comment by vincebeck** [comment]
A fixed max duration of 12sec in this case (or whatever the duration of the spell in question is) would fix the issue. I guess this could be a modular slider which the user can configure optionally within the status or the indicator.

I understand that grid2 simply takes what the game provides. However, as the ability randomly increases it's remaining duration by 1 sec when it crits, and therein reapllies the buff, the size of the bar indicator or status of the sweeping icon resets. We can then no longer compare indicators across party/raid members in any sensible way. After reapplying itself, let's say from 6 to 7 remaining seconds, it would be practical if it doesn't fill the entire bar, but rather 7/12 of it, thereby remaining synchronous in terms of rate with other indicators of the same ability.

Does this make sense?

The only current way to consistently monitor it is by using text counters, which work fine, but don't utilize the nice bar modules of the addon.

No applications of reversions would go over 12s in the current state of the game. But by making this a configurable variable, that problem shouldn't occur in the future either.

**Comment by michaelnpsp** [comment]
Try out 2.3.9-beta. 
There is a new "Duration" section in single buff/debuff configuration to setup a custom max duration.
