### ISSUE TITLE
Classic profile doesn't work in TBC with use blizzard frames unchecked

### ISSUE THREAD

**Issue by joseph3114** [michaelnpsp/Grid2#14]
This may be related to the existing issue you mentioned - but if I import or use my classic profiles with use blizzard frames unchecked, grid disappears completely. Yet a fresh profile it appears fine. No LUA errors when it happens to share but I can paste my import string if that is helpful.

**Comment by joseph3114** [comment]
[gridprofile.txt](https://github.com/michaelnpsp/Grid2/files/6508925/gridprofile.txt)

**Comment by michaelnpsp** [comment]
I cannot reproduce the problem, maybe It is rellated to this other issue ?:
https://github.com/michaelnpsp/Grid2/issues/15

**Comment by joseph3114** [comment]
Ah, that does look like the same issue, yeah.

**Comment by michaelnpsp** [comment]
Version 2.0.11 should fix the issue:
https://www.wowace.com/projects/grid2/files/3315419

**Comment by joseph3114** [comment]
@michaelnpsp confirmed working now. Thanks for the quick resolution.
Just curious, Is "use blizzard frames" a blizzard bug, or just needs an update?

**Comment by jonofalltrades** [comment]
The new release fixed the problem of Grid not working at all. There's definitely still some wonkiness, particularly with the "Use Blizzard Frames" option. For example, if I check "Use Blizzard Frames", the names status does not show up on my center text indicator. Unchecking it, however, makes the names show up again.

**Comment by michaelnpsp** [comment]
I cannot reproduce this last issue (using your profile, and with the name status linked to Frames:Player Name text indicator).
Are you sure that reloading the UI does not fix the issue ?

**Comment by joseph3114** [comment]
@michaelnpsp 2.0.11 resolved my issue in my profile.
