### ISSUE TITLE
[Question] Default Indicator Size

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#140]
I created an icon indicator to show earth shield on my party frames. When I go into raid frames I don't want the icon to be the same size. I assume I don't have to make another indicator just to have a smaller size.  I would just change my raid theme default icon size to be smaller but that doesn't change the icon size.

**Comment by michaelnpsp** [comment]
You have to change the indicator icon size, and select "Default", then the indicator will use the size defined in each theme.

**Comment by martheli** [comment]
awesome thanks!

**Comment by martheli** [comment]
is there a way to make the stack text scale with profile as well?

**Comment by michaelnpsp** [comment]
Try out 2.3.10 version. 
In this version a percent value (calculated as a percent of the icon size) can be set for stack font size option:  
- Move the stacks font size slider  to the left  (to the zero value) to switch to percent mode.
- Another posibility is to type a number between 0 and 1 in the slider edit box. for example 0.3 means 30%.

**Comment by martheli** [comment]
Does this work on indicator:icons or just indicator:icon? I was able to add the percent for my single icon but not for my icons indicator for raid debuffs.

**Comment by michaelnpsp** [comment]
Update to 2.3.11-beta
