### ISSUE TITLE
[Feature Request] Update Raid Debuffs Tab

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#141]
Any thoughts on updating the raid debuffs page to add some additional options to each debuff?

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/76448aed-b9fa-422e-bd08-8b51fc395164)

Like for instance if I wanted to change the bar color or add a glow effect to the frame if anyone got Serrated Fangs. I would just click on the debuff and check a box or select a color, instead of having to copy the debuff to another window and then manage it there.

**Comment by michaelnpsp** [comment]
This behaviour is controlled at indicator and status level. 
You can assign some debuffs to the "Raid Debuffs 2" status for example (you can add new raid debuffs statuses in "general settings" tab, and then change the color of the "raid debuffs 2" status and/or set a highlight effect to the indicator linked to this second status.
