### ISSUE TITLE
Add the new Dragonflight dungeon "Dawn of the Infinite" to the Raid Debuffs list

### ISSUE THREAD

**Issue by Heregellas** [michaelnpsp/Grid2#145]
Hello !

So yeah it seems the new dungeon from the 10.1.5 patch Dawn of the Infinite isn't in the list for the Raid Debuffs module (it should be in the Dragonflight section), if, by any chance, you can add it to the list :D 

Thanks a lot, and have a nice day !

**Comment by michaelnpsp** [comment]
Try out 2.3.13 version.

**Comment by Heregellas** [comment]
Yeah it's perfect, thanks a lot ! :D
