### ISSUE TITLE
Shaman range status bug

### ISSUE THREAD

**Issue by rogerbest40** [michaelnpsp/Grid2#149]
in the lua code of the range status the shaman is checked for eahling wave, while the default healing ability is healing surge, so if  a resto shaman dont pick healing wave then grid2 with the range status set to healing range will detect everyone out of range even ifn they are isnide.

change this line of code SHAMAN  = Grid2.isClassic and 25357 or 77472,    when it says 77472 to the id of healing surge (8004), the id of 25357 is healing wave in classic, but that dosent mean you should put the id of it in retail as it is a talent and only for resto

actually this is an issue for elemental too, not only for resto shaman (not tried enh, guess its the same for all shaman specs).
I edited that line with the spell id of healing surge and fixed it for both specs. And as far as i know (lvling my shaman yet) ele and enh specs do not even have the possibility of specing in healing wave so i dodn't know how this bug is live for so many months, maybe no shaman other then resto (healing wave is a main talent for resto) is using grid2?

**Comment by rogerbest40** [comment]
actually this is an issue for elemental too, not only for resto shaman (not tried enh, guess its the same for all shaman specs).
I edited that line with the spell id of healing surge and fixed it for both specs

**Comment by michaelnpsp** [comment]
Fixed in  2.3.16-beta
