### ISSUE TITLE
Unit Frames are blacked out in TBC Classic

### ISSUE THREAD

**Issue by jonofalltrades** [michaelnpsp/Grid2#15]
Grid2 unit frames show up as black. Player character is solid black, while adding additional players to the party shows them with varying levels of opagueness (similar to when you click on the magnifying glass under layout to preview what layouts look like).

Debug mode messages are below:
09:09:43 Grid2: DEBUG Grid2 GroupChanged PLAYER_ENTERING_WORLD Kalimdor 1 nil other 1 => solo none 1
09:09:43 Grid2: DEBUG Grid2_Grid2Frame updated Grid2LayoutHeader1UnitButton1 unit player player <= nil
09:09:43 Grid2: DEBUG Grid2_Grid2Frame removed Grid2LayoutHeader1UnitButton1 unit player
09:09:43 Grid2: DEBUG Grid2_Grid2Frame updated Grid2LayoutHeader1UnitButton1 unit player player <= nil

Tried with different combinations of "Hide Blizzard Raid Frames" and "Use Blizzard Unit Frames". Unchecking "Use Blizzard Unit Frames" just makes all Grid2 frames disappear.

Also tried with a reset, default profile, but issue still persists.

**Comment by jonofalltrades** [comment]
This is the Lua Error that's being displayed:

Message: Interface\AddOns\Grid2\GridUtils.lua:194: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed May 19 09:31:15 2021
Count: 9
Stack: Interface\AddOns\Grid2\GridUtils.lua:194: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\FrameXML\RestrictedFrames.lua"]:653: in function <Interface\FrameXML\RestrictedFrames.lua:651>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\FrameXML\RestrictedFrames.lua"]:657: in function <Interface\FrameXML\RestrictedFrames.lua:656>
[string "@Interface\FrameXML\RestrictedFrames.lua"]:795: in function `CallMethod'
[string "	self:SetAttribute("*type1", "target")
	self:SetAttribute("*type2", "togglemenu")
	self:SetAttribute("useparent-toggleForVehicle", true)
	self:SetAttribute("useparent-allowVehicleTarget", true)
	self:SetAttribute("useparent-unitsuffix", true)
	local header = self:GetParent()
	local clickcast = header:GetFrameRef("clickcast_header")
	if clickcast then
		clickcast:SetAttribute("clickcast_button", self)
		clickcast:RunAttribute("clickcast_register")
	end
	header:CallMethod("initialConfigFunction", self:GetName())
"]:12: in function <[string "	self:SetAttribute("*type1", "target")..."]:1>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface\FrameXML\RestrictedExecution.lua"]:484: in function <Interface\FrameXML\RestrictedExecution.lua:447>
[string "@Interface\FrameXML\SecureGroupHeaders.lua"]:116: in function <Interface\FrameXML\SecureGroupHeaders.lua:110>
[string "@Interface\FrameXML\SecureGroupHeaders.lua"]:166: in function <Interface\FrameXML\SecureGroupHeaders.lua:123>
[string "@Interface\FrameXML\SecureGroupHeaders.lua"]:488: in function <Interface\FrameXML\SecureGroupHeaders.lua:387>
...
[string "=[C]"]: ?
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\Grid2\GridRoster.lua"]:292: in function `GroupChanged'
[string "@Interface\AddOns\Grid2\GridRoster.lua"]:240: in function `?'
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by michaelnpsp** [comment]
It seems you an incorrect version of Grid2 is installed, working version for burning crusade is: 
https://www.wowace.com/projects/grid2/files/3313057
Try reinstalling the addon.

**Comment by michaelnpsp** [comment]
Forget previous comment, It's a bug in icons indicator, a workaround:
Goto DispellableDebuffsMultiple Indicator configuration , layout Tab.
Set Border Size to Zero.
I will update the  addon to fix this issue in a few hours.

**Comment by michaelnpsp** [comment]
Version 2.0.11 should fix the issue:
https://www.wowace.com/projects/grid2/files/3315419
