### ISSUE TITLE
[Feature Request] Show Debuff Tooltips

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#151]
I know this was talked about but I wanted to create an open feature request for this. I would like an option that would add the ability to hover over raid debuffs (and possibly any debuff indicator) and show the spell tooltip.

**Comment by michaelnpsp** [comment]
Sorry, after checking this posibility, adding tooltips to icons will block clique and mouse over macros from working, if  the cursor pointer  is just over the icons, and all workarounds that i know to avoid this issue are too resource expensive.
So i have to decline this request.

**Comment by michaelnpsp** [comment]
Implemented in version 2.6.20-beta:
- The feature must by enabled individually for each icon/icons indicator.
- Watch out the "Display tooltips" option in each indicator settings: layout tab (disabled by default).
- This feature does not work for indicators positioned outside the unit frame.

**Comment by martheli** [comment]
@michaelnpsp thanks for working on this. Is there a way to make the tooltip match the standard blizzard tooltip? So when you hover over a unit it shows you the tooltip on bottom right of the screen by default but when you hover over a debuff or buff, it shows you the tooltip anchored to the mouse cursor I believe.

**Comment by michaelnpsp** [comment]
Not, but the feature is not finished yet, there are missing settings. 
The tooltip position and anchor point can be configured in  Indicators/Tooltip/Layout, but now is always aligned to the main grid2 window if the non-default anchor is selected.
I have to decide yet if the anchoring should be configured per indicator or not, allowing diferent anchors for different indicators.

**Comment by michaelnpsp** [comment]
Update to 2.6.21-beta.
Now there is a tooltip anchor setting on each icon indicator. 
If the anchor setting is not set (default selection) the anchor specified in the general tooltip indicator is used (Indicators/tooltip/Layout)

**Comment by michaelnpsp** [comment]
Update to 2.6.22-beta.
Some bug sfixed and now  tooltips for icons indicators can be enabled and configured just in Indicators/Tooltip.
