### ISSUE TITLE
[Bug] Unable To Move Frames

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#153]
You need to have border set in order to drag and move frames. If you have no border on frames, then theres no way to drag and move the frames:

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/854ee9dd-c989-4129-af6a-9362aef86f05)

**Comment by martheli** [comment]
@michaelnpsp  why was this closed?

**Comment by michaelnpsp** [comment]
Because this is not a bug.
