### ISSUE TITLE
Cooldown Text

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#160]
Is the only way to get cooldown text to show up to use OmniCC? I have elvui and I have cooldown text on and on my elvui frames it shows up but on grid2 frames the cooldown text doesn't show up unless im using OmniCC

**Comment by michaelnpsp** [comment]
You can configure OmniCC to add cooldowns only to grid2 icons.
Another posibility is to create extra text indicators in Grid2 to display cooldown texts.
