### ISSUE TITLE
Get a more complete raid debuffs list in dungeons

### ISSUE THREAD

**Issue by Carglass** [michaelnpsp/Grid2#162]
Hello, 

I would like to ask if you would agree to evolve the raid debuffs list in dungeons to include every debuff, in particular when it comes to trash mobs. It is of course possible to tune the list manually, but it is a process that needs to be performed every tiers and is not easy to share with others to my knowledge. I would think it is reasonable to have them all since users can disable them or they could even be disabled by default, it is really the looking for Spell IDs part that is lengthy.

I am asking for your opinion since there may be reasons you would not like to have this. If you agree, I would be very happy to submit a PR to update the S3 dungeons with the entire list of debuffs, including Trash. The raid debuffs module is the biggest strength of Grid2 and I would love to help making it even better!

**Comment by Carglass** [comment]
I am working on compiling these debuffs in this document https://docs.google.com/document/d/1boPZkwMuVflxO9p6qXTenB1eZoPv8QkZCYdTVm7wgyE/edit?usp=sharing

**Comment by michaelnpsp** [comment]
I have no problem adding missing debuffs, but unfortunatelly not many people report missing debuffs.
But aboute private debuffs, i think these should no be added to the raiddebuffs module, because they cannot be displayed by non-blizzard addons.
To display private debufs there is a special indicator in grid2: "PrivateAuras", private auras indicator defines a zone in the unit frame where the game will display private debuffs.

Maybe I could think on adding private debuffs, but marked as especial or in a different section,  for information purposes only.

**Comment by Carglass** [comment]
Sounds great about the missing debuffs, I'm compiling the list in the gdoc I linked, I can also put up a PR tomorrow if that works for you? That's exciting, I think people will love having everything day 1 in dungeons. 

I dont think any of the dungeon debuffs are private auras right? However I did see the indicator and will try it out on Nelth to see how it works :) 

Another question for you, is there a way to contact you privately? I am working on guides to use Grid2 as well, I thought this could be of interest for you maybe?

**Comment by michaelnpsp** [comment]
It seems they are not private,, at least wowhead does not mark these auras as private.  i simply wrongly asumed they were private because the spreadsheet says that highlighted auras are invisible.
Private messages can be used in curseforge or wowace to contact me.

**Comment by Carglass** [comment]
Oh I see, my bad! I reformulated.

**Comment by Carglass** [comment]
I updated the gdoc with the debuffs from Throne of the Tides. I think I am just short of testing the new version of Yalnu to check if new debuffs have been added so I think the ticket can be closed, and I can submit another one if I find something else during testing :)
 https://docs.google.com/document/d/1boPZkwMuVflxO9p6qXTenB1eZoPv8QkZCYdTVm7wgyE/edit?usp=sharing
