### ISSUE TITLE
[Feature request]AOE Heals status but for damage events?

### ISSUE THREAD

**Issue by holypalaswe** [michaelnpsp/Grid2#164]
Similiar to how you can add spells to the AOE Heals status and choose active time after that friendly spell has hit someone, but do this for damage events instead. 
Use cases being things like marrowgar coldflame that has no debuff on players when dealing dmg

**Comment by michaelnpsp** [comment]
Update to version 2.3.22.
AOE Heals section was renamed AOE & DMG, and now satuses to track generic spells can be created.

**Comment by holypalaswe** [comment]
Great work!
