### ISSUE TITLE
Unable to filter header by role on classic 

### ISSUE THREAD

**Issue by mech422** [michaelnpsp/Grid2#167]
Sorry if I'm missing something obvious, but I created a custom layout - added 8 headers (1 per group), a 'by-name' header (works really nicely!), and a 10th 'tanks' header (all 8 groups checked, only 'MainTank' role checked)...

Everything works except the main tank header - that displays ALL members with the MainTanks sorted at the front/top.  I'd like to ONLY display MTs in that frame/header?  I looked thru the bug reports and tried turning blizzard raid frames off, and tried with no other addons loaded. I saw https://www.wowace.com/projects/grid2/issues/748 - not sure if something similar happened with the big patch a while back? it seemed to break a lot of stuff...

I'm using Grid2 v2.3.21 from curseforge.

Thanks!

**Comment by michaelnpsp** [comment]
Are we talking about classic (vanilla client) or wotlk (wotlk classic) client ?

**Comment by mech422** [comment]
oh - sorry - classic vanilla

**Comment by michaelnpsp** [comment]
Update to version 2.3.22-classic.
You have to re-save the customlayout: simply goto to the custom layout configuration and uncheck/check some role option (this will save the custom layout with the correct role filter).

**Comment by mech422** [comment]
Upgraded to v2.3.22-classic via curseforge (game closed, files not in use) - no change unfortunately :-(

**Comment by michaelnpsp** [comment]
Are you sure you change something in the cutom layout to force a layout re-save ?
You can send me your profile in text format, you can export the profile from "Profiles/Export&Import" tab, important, check the "Include custom layouts option" before exporting the profile.

**Comment by mech422** [comment]
I changed the roles selected, groups selected, changed them back and reloaded ui...
I'll try some more after dinner

**Comment by michaelnpsp** [comment]
Check that the latest version is installed (In the About tab: "Grid2 2.3.22" should be displayed).

**Comment by mech422** [comment]
yep - grid2 v2.3.22 in about ... export is : 

[=== Myrakalear-Mankrik profile ===]
3074D6E30052292566144557B82AD509AF500413C407C84D23AAA76046A158B6
226B145D732AA1708EC982BE84A45918425A2D141285800D341253112A8B8051
B1984F15846429417212A2B294A455F294A4A99425DD4882DE49CF422A1A0193
A01552B41A297A8C45A27594A4C6500A2F5108C8500A47694A45CE55F7108AA1
C448E035A5C01E1355623057990B95A8FC25A1D4293D056534459A7D24866B45
7B982BB94CF6491E22D1788A2693AA7E2AA9E0ABE24D6700C7700D8712A3F09C
A7228DF059A7DBB94DE6417C0CEBAB541B81EE62F2EC12391232A1B17789FE6A
C55C0021BEC60C927513088BC260E107AC55C002257B821C70C902B6BDE24AC8
30831A2CCBE260C927513088469344D083C9CB8378C46AE615C2689FE620885A
667B82613CDD5A7739CC64643BE1BC49CF2D31445A26A4BB5490E35BC95C9A41
BE050F94F41B281CC1940F866D369927523CBCFDD423B191DCA7C2352FB4F41B
281CC1940F866D3699275235BC95C9A41BE050F9CF1E50ADD423B191DCA7C235
2FB4F41B281CC1940F866D3699275235BC95C9A41BE050F9043CBC8DD423B191
DCA7C2352FB4F41B281CC1940F866D3699275235BC95C9A41BE050F9C81E59CE
6299D8C866D369929F5A7A851C06E8428743BE1BC49B299A5EC2E45A857828F4
9C0F2CFE6299D8C866D369929F5A7A851C06E8428743BE1BC49B299A5EC2E45A
857828F48F1E52FDD423B191DCA7C2352FB4F41B281CC1940F866D3699275235
BC95C9A41BE050F94E3CB08BB9466323A95F856A4E79E926503893290E1DCA7C
235EA46A693B835926D1A0E31078756BB9466323A95F856A4E75235CA0603742
1C3A95F856AC5A725CAC48A3693C94DEB55226A85718C79A5E231C11C91045C4
0016A08371222A0E8C7763213B62080350C9B01115074EB3B1989762080350C9
B01115074E745C619F1517C619F151B5B3CB478DD4C957125CA341C72462202B
112A070712F5D0E44057C1C58C746320275E2249A519FE2249A57AC91788CA08
A260E909B2460700CE41B281CC1940F866D3699279139CC64643BE1BC49CFA46
2590B061CBCAC4C48C6404EAC54825BE0729908677317B81870C925BC12A60C9
276D9D08395E241B30E0783C1E415C130BF11890532C6FC773C92A83606F5DD2
A85C077310A5F226BC95CA08D98848137131067C42840BC1C8B5264BAC24927B
2318B5220A5F226BC95CA0872046C1C2830E510D9C425E65624D9971174C4DD2
A85C03FDD469B05CE40882CD213A83B83D98B5C0C3102A07B44C5CAB0CD21102
08142103F9276D9D40882CD213A83B83D925BC12A620441E69815C95C9E07242
B06036A4B758900DA711B5EC2650C8BEA086D31976BB02C4288B4F425E656209
1C2F4BB54D411A304B8AC72046C1C28748B4F408C838507C5750472315A6D3C4
96F2D162BA87A26C7272984AE8325739C0350399D4193F892BB9458185C881E4
84C27C026C49C773104C253BB541B81207779E9C94229A3E84DD5EF25066EB6D
9182BC4B1E3053E3CD8968171869A968C3BC4B10C004938290EB11E6C43043C9
00269A9DD2A85C0D8DD5A7272984AE8325779FB41899FA5760AC23D68F04D8F0
736A16C50A5A62E576942279B609C1499C5E87D736A16C0720441E69815C95C9
AE00CDD5A7272984AE8325779FB41899FA5760AC23D68F04D8F0736A16C50A5A
6A12FC23D60E5E986D020A6C78B13D00D0720885A667B82613C46779E9C94229
A3E84DD5EF25066EB6D9182BC4B1E3053E3CD8968171869A92F060EDF44E1082
7CBE0040AEB13D03683102A07B44C5CAB0CD2110208142103FDD5A7272984AE8
325779F75212C50ABC4F3481E4001B4DCE615C2680ADD5A7272984AE8325779F
B41899FA5760AC23D68F04D8F0736A16C50A5A662023C0066873C701E146005E
9DD896813C900158B526417617ABBB4F4E42194D174AEE2FFA4248B04799E780
3C900158B526417617AA381BBB4F4E42194D174AEE2F792033F5BEC04EBF270A
C186480736A16C50A5A62E5769422FCC0F181C097034FD896813C900158B522E
26D50E6980010C029089BFBBB4F4E42194D174AEE2F79203B4C03C709FA570D9
00346736A16C50A5A6A12F40464093E1868F0C4C0056736A16C0720441E69815
C95C9AE00ADD5A7272984AE8325779FB41899FA5760AC23D68F04D8F0736A16C
50A5A662023C0066873C701E146005E9DD896813C900158B526417617AA38FBB
B4F4E42194D174AEE2F792033F5BEC04EBF270AC186480736A16C50A5A620330
20D009F991870A10A4C7FF6C43291E4001B4DCE615C268A3CEE2D393944257C1
9ABBCF5A0CCC7DA330569963C70A6C78B13D03E20D25331CB1910D7C3033FD70
105EE78B13D00D0720441E69815C95C9AE02FDD5A7272984AE8325779FB41899
FA5760AC23D68F04D8F0736A16C50A5A6205E68C1FA3902FC43ED79BFAF6C43C
81E4001B4DCE615C268BBB4F4E42194D174AEE2F79AC5E0CC2080F1208C00668
F01E6C43C8B04B4D4C3E18104EBC1499FE3828112CD8968C783102A07B4C82EC
2E4570CFEE2D393944257C19ABBCF5A0CCC7DA330569963C70A6C78B13D03E20
D2535E0CC0F9184E68EC29C08040AEB13D03683102A07B4C82EC2E457846779E
9C94229A3E84DD5EF25066EB6D9182BC4B1E3053E3CD8968171869A92F060EDF
44E10827CBE0040AEB13D03683104C253BB541B812E7779E9C94229A3E84DD5E
F25066EB6D9182BC4B1E3053E3CD8968171869A9270668FC0490033FD8C2301E
3CD896813C900269A9DD2A85C03BDD5A7272984AE8325779FB41899FA5760AC2
3D68F04D8F0736A16C50A5A662EBF681049BF10460E1402F3CD89608683104C2
53BB541B81AFBBB4F4E42194D174AEE2F792033F5BEC04EBF270AC186480736A
16C50A5A62033020D009F991870A10A4C7FF6C43291E4001B4DCE615C2682FDD
5A7272984AE8325779FB41899FA5760AC23D68F04D8F0736A16C50A5A6205E68
C1FA1F8F087F1FEBF648B13D03683C90C20A5F4520CA64850B0E9F4967B821C7
2FAB595A30E4D27617A1141F45C8F4E42194D174AE624269BAD9BC4F34890091
70B0EE4442C89B8900B36214285E06CD21D136D1269E4651F45C87EBB1E406C2
F4BB54548ED3A83B83DC70C926503893290E1DCA7C2352FDD0724269308DB290
16204BE54C693B851074D510DA7204BE54C693B8510748B20A1F9C4086DB88D2
761B2060CB20A5F408C83850F8AB20A399A5EC2E43282E9A81FC773C945C8362
18920D6F107A693B83553C836218920D6FC773C944424E6D9A48C44EBBB4FE62
04BE54C693B8510B3119036E2620CE894090693817B4C86595825E656207B440
4BE54C693B8510F408C8385070CB20A399AB541B816EBB9C271A8D9A892262E6
130F4001B4DCE615C26835ECA3B900269A9DD2A85C07A4D2788A900269A9DD2A
85C078310A5F226BC95CA0810FA086D31976BB02C4288B4F425E65624D997117
4C408C83850F8079E9009170B0E8BEA08E462A4DA7892DE5A3C4D27617A1141F
45C87EBB1E4086DB88D2761B206C57504BE90985E814C8929FE620885A667B82
61340EEE2D393944257C19ABBCF5A94202CB190E39424627091648B13D00D50A
5A66227096D0AC239301F121F181E6C43043C900269A9DD2A85C0D8DD5A72729
84AE8325779FB43940487321CB6C76A330628F0736A10AB04B4D43080C060E57
2942646A1F0C0736A10A1E40882CD213A83B835D129DD5A7272984AE8325779F
B41802F5768705698C31F1891E3CD8968171869A9942EB127FD097699C330A10
C0736A10A1E4001B4DCE615C2689CEE2D393944257C19ABBCF5A270AF104A5BC
1F98F10891E3CD8968171869A99082420C010F27D8F068C1F1E6C43043C90026
9A9DD2A85C014BBB4F4E42194D174AEE2F79AC18E70096D27C72E700668F0736
A16C50A5A6A10406030FA39421323D87068B13D00D0720441E69815C95C9EEE2
D393944257C19ABBCF5A04D91E188734EE30D80104E78B13D03E20D253D0CB6D
6468F44EAD70184BF1E6C43043C900158B526417617AA381BBB4F4E42194D174
AEE2F792ED7304EBC5B6F5E0409E4CF0736A10AB04B4DC4470F31D87D68FE722
7C303CD89608683104C253BB541B81AC7779E9C94229A3E84DD5EF25930DF002
DA5E8F4CF00CC0F1E6C43C8B04B4DC44E02DA149562702E342E303CD89608683
104C253BB541B81AE0BBB4F4E42194D174AEE2F79205E87C38080401E1F87CBF
AD00DD8964271869A90C027F30E1F27C384EAD793E3BB13D03683102A07B4C82
EC2E4570F7779E9C94229A3E84DD5EF25CBF608C79B6DEBC1802D98F1E6C4304
71869A960E5E27D27C7260033F1F1248B13D00D0720885A667B82613CDD5A727
2984AE8325779FB45E8FC21F5BE0108910300348B13D03E20D2531827062AD03
0F952A33D0A42BB13D03683104C253BB541B812E7779E9C94229A3E84DD5EF2D
42101ED840F942123938C032CD89608E20D25331058408120E5EA1F1C093E3CD
89608683102A07B4C82EC2E45709FEE2D393944257C19ABBCF5A0409FA33C382
B44E98F0CC0F1E6C43C8B04B4DC42B4240C3808E7030F270A11E6C43043C9002
69A9DD2A85C05BEDD5A7272984AE8325779FB439C24800A08FC21091608C7D73
6A16C50A5A6A10C00C4C73C70AC31D90E348B13D00D0720441E69815C95C9AE0
0CDD5A7272984AE8325779FB41FEB102F5EA5BF27028472E78B13D00D50A5A66
295202D991A180A423CB112CD89608683102A07B4C82EC2E4570CFEE2D393944
257C19ABBCF5A87FD009F27DAD793014A31F3CD89608E20D253394C7930394CF
4080297093E3CD89608683104C253BB541B8166BBB4F4E42194D174AEE2F79AC
D730F68F0A0646940CB6DAF6C4329B04B4D40609BF10F8793E1427DEBC1F9DD8
96813C900269A9DD2A85C0DFDD5A7272984AE8325779FB43940487321CB6C76A
330628F0736A10AB04B4D4066A38F608213CF4C844BF1E6C43C81E40882CD213
A83B835D104BBB4F4E42194D174AEE2F792014EBEC0F0AC21972E3033C78B13D
03E20D2533909560206290018EB1A1F0C0736A10A1E0720B086D35900BA1161C
287E35ADD2A40F9CBE6569E0835BC95C96405C3513E393944257C19AB90985EA
67E23DF01624269308DB290162BA87A26C3FDD07203697ADD2A224FE15C95C96
E30E41B281CC1940F866D369929FE6839A817C420350ADE30E408C8385077222
16CC5C408D139021C2703E698E81BE01B47204BE54C693B8510748B20A1F9C40
86DB88D2761B20E8AB20A5F408C83850F8AB20A399A5EC2E45D03E89406A04BD
3FDD07242B06036A4B7589CA2E9A81F9C94229A3E84DD425E6562091C2F4BB54
D411A304B8AC783C1E415C130BFBB94581850067C42840BC1C8BC2606927B231
9F5EF489206CC3B091FC77397C8B228B9095A6671D0CDD4D9976126C49DD48AB
2C4C54742689207272984AE8325735AC0350E4E42194D174AE6A8CB2C07288A4
5C4932F4C69B89AB00044FB2B927C4288B291E4E13EA80E6228148C46627CA55
1CDD4D9976126C49DD48AB2C4C54742689207204947E42195C58C549A1735AC0
350E40829EC9422B8B09B8253E6A8CB2C07288A45C4932F4C69B89AB00044FB2
9927C4288B291E405442431CC00A2BB902A25131411907AECC3B0136ACE624D5
6C4C54742689207204947E4219D925689207204947E4219D922FA03C9AB00044
FB0F3141190BB05A58AAB0F353C41848940179E03C903F8926671D0CDD40159A
8903F8923576E95881356731AEA03171D19816A0C94D174AE6A4916A0C94D174
AE6A8CBC4F7835710088E7107A68920903902E20E4936214C5ADF1E4806C1C28
FE62F8576C5FE62B7589017589ADB2C4CFA03C902A2513128170B0E3C9016DB8
8D2761B20EDD40159A89016DB88D2761B20E1E4897C413D31A041C7731445A26
2CC36AC4D9976126C49DD48AB2C4C54742689207A86C927838B6A4916A0C92A1
7AC1E0EA922FA03C9AB00044FB08353C4184894017107AC13902E2D6C072590B
D1AAC4F8576C7731445A262485E6A7CA33E3C903F892627CA551CDD40159A890
3F8923576E95881356731AEA03171D19816A0C90712715A6CD4923C41831E24E
2A4D8B922F2F7835710088E7107A68920903902E20E4936214C5ADF1E4A216B7
E6A7CA33EBB902A251312C273D36D91F1E4091BE01B47731445A2628C857885A
35EA26001911D8D8B3C107AC55C00A36CA34C2DBC81E46B7AA2BBB902A25139D
E9AACE07282221A906600513D36D91FDD40159A890A88486A7CA33E3C9452C6F
C7731445A262485E397CA33EA7739DB2C488B2C4DE5162E7581E4651F45C8B36
39A48DE0553576E95881356731AEA03171D19816A0C92A17AC1E0EA925689207
A86C927838B6A8CB2C07AE20001DF2D31B4DA78144D510DE72314119036E26A8
2E61C89050E072590BD1AA6731445A262485E3576E95881356731AEA03171D19
816A0C92A17AC1E0EA925689207A86C927838B6A8CB2C07AE20001DF2F72F857
6C5FE62B79E9017589ADB2C4CFA03C90A8848137135417B06C4820783141190D
C83DDD40159A890A88483576E95881356731AE23183171D19816A0C9C9422D49
23C418393944A922FA03C9AB00044FB4E3141190BB05A58AAB0F353C41848940
171078397C8B228B98060123999D54307731445A26AC19726BC5C4D9976126C4
9DD48AB2C4C54742689207204947E4219557C19AB925689207204947E4219557
C19AB922FA03C9AB00044FB299C36D917DBB9CE5A724C5A7A6F2D31FB4F07AC1
3902EA4683141190DC8353D36D91FDD40159A890A88486A7CA33E3C9C36C511C
D48C253936DAA0EE6AECC3B0136ACE624D5162E2A3213C4183939442C58C549A
1735AC0350E4E42190712715A6CD4197581E40159A89274E98D27135710088E7
5635E894017523C927C0C2C44038099C673576E95881356731AEA03171D19816
A0C90052D9394467A4916A0C90052D9394467A8CB2C07288A45C4932F4C69B89
AB00044FB2B927C4288B291E07AC1A5817E22FDD406C8B0F026C49DD40159A89
0C8171E14C892397CA33EA7739DB4F4CFA035B79E9017581E07A851C0A989206
119BB902A25135CA060D4C410B88C1E4A216B34599061D06E1607731451719BA
8570F510D129902A25139A48DE05562854389781C9C36D917DBB9CE5A72E79E9
ADB4F488B4F0783185022E6A13195BD26EDE6288A45C4061888B96C1A25135E1
32C1A251312B6B5CCB9C36D917DBB9CE5A72E7504BF35B75043E724C5A783C98
B55A516B3CDD40159A898B55A516B3C90C2A1B17787504BF9C42ABD43710EB20
A3998B55A5179F0C9C36D917DBB9CE5A72E79E9ADB2C488B2C0783176D5CE62F
8576CDFDD46F2D31FB20A399ADB4F488B4F07288A45C4C9571397CA33E1DC265
0E5EF4E1BEC8BEDD46F2D31FB4F4DE5A724C510D9C0783122E6A131798693308
0556AC0354CE62F8576C5FE62B79E9017589ADB4F4CFA08E46831445A26244CD
4339C0354C0835E9A8EDBCAC4C50CC048F1E423B9341CDCEC8141C7731445A26
299DC1A0E6676C0A0E397CA33EA7739DB4F4CF2D35B750472312EA03C1E40D2F
650CDD40159A890A5EDA08397CA33EA7739DB20A5E9C4CFA0860E4DE510D0C90
1750430783C98B5C0C6285022E6A9C7731445A262E6130B9061888B962F90C20
1173D4EBB1E4E1BEC8BEDD46F2D31FB4F4DE510D9C488B4F07839A48DE9B9892
E13916A4BBB9A9E6BDCFA031445A262590BD373135C3623C4967295CD126967C
40FB4F4892E5F81C209AB5490EA648DE9F889C36D917DBB9CE5A72E7589ADB4F
488B2C0783185022E6A13D1A251D54E9FE6288A45C4061888B96C1A25135E132
C1A25139345A2AB8C3F9C36D917DBB9CE5A72E7589ADB2C488B2C07831451716
1EE62F8576CDFDD46F2D31FB20A399ADB4F488B4F07288A45C4055C5858397CA
33E0ADD46F2D31FB4F4DE5A724C5A78312A36A4447A2E22751BE0E1072F8576C
3A95CA0CB04397CA33EA7739DB4F4CF2D35B7589017581E072E6130B9897C413
1A5EDA08BB902A251317B818D4CC36A890D2F650C9C36D917CFE62B79E98F516
A6FA0869BE90179E1E4C25BE16015750472397CA33EA7739DB4F4CF2D35B7504
76EF488B2C072F8576CDFDD46F2D31FB20A330E4DE510D98C724C5168397CA33
E6CE62B79E98F510D1C89ADB20A3B4624C5168397CA33E1DC2650E50C9C36D91
70DE62B79E98F510D040D4DE510DEBF312EA08EC68397CA33E0CDD46F2D31FB2
0A330E4DE510D910724C510D91078397CA33E9CE62B79E98F510D2F9ADB20A18
EF488B20A182F468397CA33E2FDD46F2D31FB4F4DE510DEB1312EA086D870E07
839265626731445A2625CAC4C0720B0B055BB902A2513185858AA9C36D917DBB
9CE5A72E79E9ADB4F488B4F078317161C823D3590F22EE628A2E22751BE0EB47
8902A251317161C823D3590F22E4E1BEC8B1BB9CE5A72E79E9ADB2C488B4F072
F8576C3A95CA0CBC89C36D9170DE62B79E98F5A7A6FA0312EA03C9C36D917F77
39DB4F4CFA035B79E9017581E4E1BEC8BEDD46F2D31FB4F4DE5A724C51683C92
5002DDD40159A8925002D9C36D917DBB9CE510D2F462E7589ADB4F488B4F0783
97C4680B0D4916A88DD40159A89C362348586AC0354C4E1BEC8BEDD46F2D31FB
4F4DE51624C51683C9C36234858BB902A251397C4680B072F8576C5FE62B79E9
8F5A7A6FA0312EA03C1E4888B96C4C520977C00805C24C8926AC0354CE62F857
6C5FE62B79E90175043E7A6FA031FB4F07288A45C4888B9662916A88107AC351
DB795998B4E2736839CCA267731445A2629955CE4E1BEC8BEDD46F2D31FB2C4D
E51624C5A783C9AB0B061C7731445A26AE2C2850F9C36D917DBB9CE5A72E7589
ADB20A5E312E2D3C1E49230828FE6288A45C49230828F4E1BEC83E7739DB4F4C
FA08636A6FA0312EA0860E072F8576C578DD46F2D31FB4F4DE510D87D312EA03
C9C36D917DBB9CE5A72E7589ADB20A3990179E1E4E1BEC8BFBB9CE5A72E79E9A
DB2C488B2C072F8576C3A95CA0CB4789C36D9170DE62B79E98F5A7A6FA08E462
4C5168397CA33E9DE62B79E98F510D270207A6FA086F39C624C510D956EF072F
8576CD8DD46F2D31FB4F4DE5A724C5168397CA33E0CDD46F2D31FB20A1435B75
0472EF488B20A3B1E4E1BEC872BB9CE5A72E7589ADB20A18312EA0860E072F85
76C5EBB9CE5A72E7589ADB20A3990179E1E0720B044CD43622385E2C6E267314
45A2620B044CD43E059A892F811E059A89091C2716371397CA33EA7739DB4F4C
FA086CF4DE510D6C488B2C07835AC00A0E6B3CDD40159A8925600507BD1E4E1B
EC8BEDD46F2D31FB4F4DE51624C510D9C07835320B65131C2C245DE6288A45C4
D80CA55C40B0B055397CA33EA7739DB4F4CF2D35B750472312E2D3C1E4061888
B96C442685EC49DD40159A890C201173D8345A26AC3648345A26242685EC499C
36D917DBB9CE5A72E7589ADB20A1F312EA03C1E4E57B97EE1BEC8FE6288A45C4
E57B97EE1BEC8F4E1BEC87EBB94D25A6D29400510875B4127E6739DB4F4CFA08
E46A6FA08E4624C510D9C072531BCCA2C030FE62B79E98F510D99F35B75043E5
E312EA0860623C90794649A5076739DB4F4CF2D35B7504768F9017504B1A7831
2B112A076739DB4F4CFA086F399ADB20A5E0C901750476EF0724648C892BB9CE
5A72E7504726C4DE510DE72312EA086C763C9091C5A614E099DD46F2D31FB4F4
DE510D646312EA08E06C0724652B4DABB9CE5A72E7589ADB4F488B20A39C6831
238311C9A15B612715A6CDE62B79E98F510D279F4DE510DADF9017504BF0A1E4
83D58C4820D6FDD46F2D31FB20A5F4DE510D0A9017504763C900411071E24E42
17DE62B79E98F510D270E4DE510D87D312EA0863043C90907127834E6739DB4F
4CF2D35B79E90179E1E484114D320238C5DE62B79E98F510D91E7A6FA08E4299
017504BC143C900411079AB464BA57739DB4F4CFA08E40435B7504720A901750
4760A1E4A6429C127AE83BB9CE5A72E79E9ADB20A5F488B20A5F07246070959C
253A6927838B6739DB4F4CFA086CB135B7504BEC624C510D2FC6839A5A4DA529
00A200F8483E6739DB4F4CFA035B79E9017581E44A62202B11A6739DB4F4CFA0
8EC0F35B7504729C488B20A5E0A1E4082C6E07739DB4F4CFA08ECC89ADB20A5E
8F9017504BF0C1E4A64D25E0707DE62B79E98F510D879F4DE510D040D488B20A
D84683C9C36D91753C278857130E072F8B0B036E2C36D91FDD40159A89C3E2C2
C89B0F8576C72F8576C3FDD4A6925B694208A00CBA5A0937BB9CE5A72E750472
35B750472312EA08E4683123246C49DD46F2D31FB20A399ADB20ADF4624C510D
8FC6831E471231A04BD7739DB4F4CFA086D35B750438624C510D9D072531BCCA
2C030FE62B79E98F510D99F35B75043E5E312EA0860623C90058DC1EE62B79E9
8F510D99135B7504BC399017504BF0C1E4A6429C127AE83BB9CE5A72E79E9ADB
20A5F488B20A5F078397CA33EA685E01BE260C1E4A216B34599E5CC9B050EE62
F8576CDFDD46F2D31FB4F4DE5A724C516831445A262590BD1AAC4F26EC582072
F8576C14BB9CE5A72E79E9ADB2C488B2C072F8576C3A95CA0CB04397CA33EA77
39DB4F4CFA035B79E9017581E072E22F89371E14C892BB9C36D917F7739DB20A
5E9C4CF2D35B79E9017581E40159A898B8C36EC5870136AC4E1BEC8743B85187
9F397CA33EA7739DB4F4CFA035B79E9017581E07AC54F66731445A26AC54F662
F8576C5FE62B79E98F510DE7235B79E9017504BF9C078397A2BC5620CBB902A2
51397A2BC5620C397CA33EA7739DB4F4CF2D35B7504BE9017504BE1E072E6596
5CE6288A45C4CDA2DA890C2A1B17787504BF9C42ABD43710EB20A3998B55A517
1808397CA33EA7739DB4F4CF2D35B7589017581E07248554285CC48A2E2C2CDD
40159A89016519061331AA8B0B072F8576C5FE62B79E98F5A7A6FA0312EA03C1
E4CD26063D6E936934BA0CDD40159A898B5C0C6ADC37C2786518397CA33EA773
9DB4F4CF2D35B7504BF9C488B20ADF1E072BD44CDD40159A89C631172F8576C5
FE62B79E98F5A7A6FA0312EA03C1E423499A216B7E626A87C46892DEE6A6ABD6
3FB2C40159A8946823552C6FCD4C41F89C035AD946177885AD131CF2D397CA33
EA7739DB4F4CFA035B79E9017581E07200816E98DD40159A890006897262F857
6C5FE62B79E98F5A7A6F2D312EA03C1E4CD2606313F89266ADD2A40FDD40159A
898B5C0C626E135CC4BB5490E397CA33E8FDD46F2D31FB2C4DE510D27D312E2D
3C985A6D3C02AE2D397CA33EA7739DB4F4CF2D35B750476EF488B2C072F8576C
DFDD46F2D31FB20A330E4DE510D98C724C5168397CA33E6CE62B79E98F510D1C
89ADB20A3B4624C5168397CA33E1DC2650E50C9C36D9170DE62B79E98F510D04
0D4DE510DEBF312EA08EC68397CA33E0CDD46F2D31FB20A330E4DE510D910724
C510D91078397CA33E9CE62B79E98F510D2F9ADB20A18EF488B20A182F468397
CA33E2FDD46F2D31FB4F4DE510DEB1312EA086D870E07839A48DE05566760077
31451719BA8570F510D6C40159A89452C678A23B3308397CA33EA7739DB4F4CF
2D35B7589017581E07A68362410B7CA33EBB9C36D917F7739DB20A5E9C4CFA03
5B79E9017581E40159A89A1E89050CE1BEC8F4E1BEC8386739DB4F4CF2D35B75
89017581E4E1BEC8743B851871862F8576C5FE62B79E98F516A6F2D312EA03C1
E423BA85BD1EE6288A45C423BA85BD1E406C2F4BB549345A2E2F72F8576C5FE6
2B79E98F516A6FA0312E2D3C1E4061888B96CC8E897E26731445A2620B044CD4
3E059A892F811E059A892A36E9B89C36D917DBB9CE5A72E75043E7A6FA0312E2
D3C1E4CA96A36A88DD40159A89853D47C411397CA33EA7739DB4F4CF2D35B79E
90179E1E07260080EA216B36A4BBB902A25131300407590BD135AD9C36D917DB
B9CE5A72E75047235B750472312E2D3C1E4D91049955CEE628A2E22751BE0EB2
0A5E9C40159A89A330823BA8D9C36D917DBB9CE5A72E75047235B75890179E1E
078353C8BCC248892DEE6AC587C4107E83DD6A9B00B4917995839AD0C9F4D992
D223137B0136A014BE544923E23B0725B1A573A6F4D60E9A335A54648789CC67
923E23B0725B1A57335EA26C1223137B0136A014BE544923E23B0725B1A343A6
F4D60E90350001C1223137B0136A014BE54C1139C035268227C9E63DC5085AC8
BCC2C94D6069D49BA81788C80F0399DE256C5661E4A634786683100287E81352
FDD415C130BF796F7A82E818D7C56130323201173D4E7913C9278616C932B63D
DD4E13EA80E62469A9D5430773122E6A1317904ED1300241B0136A8923C41175
69D072590BD1AAC4F8576C77397DD6E9B7CA33E7569D07282221A90660059DD4
A85998B2BC6839A48DE9B9E1BEC8FE62FABDC37F8576CFAC2B1E4897C413BB86
0EE62E6130B9897C4133DE61528F5A3946AE2C2850FB4728F983BE2E2D98C783
9DE9AACEE626D43D1354C599C72E65965C59563185858AAB230E072F81754073
12B4D4E85BA28BB901173D898B44BC91048A23568922EAC2B1E4A216B7EBB945
2C6FCD4C41F89C035ADB2BC6839A48DE055BB9452C678A23DB89371A0CB2BC68
3141190D403308A89E1BEC8FE62FABDC37F8576CFAC2B1E405442433E477397A
2BC5620C71E399A1185BA8906161AAEAC0F39A48DE05562854389781CB29031B
6A9E8922EAC043185858AAB2B4683141190DC8353D36D91FDD4E9AC279900F58
F46A6406DA26285858AAB23CF4A216B34599061D06E160FA42C4CA96A36A88B2
30D406161AAEAC291E4806C1C28FE620B044CD43622385E2C6E2E2C789452C67
8A23B33087529C4061888B96C442685EC49B081628697B20E594890C201173D8
98CAD613FEAC2C4061888B96CC8E897E2E29781E4897C413D31A041C77317161
C823D3590F22E5A390317B818D40B044CD439F5AD84620B0B05579E4291E0728
A212319FE621A8544710EDD4061D8D8B3CB4F4CD260EB4F072C41036E958C87E
BBB4FE68758DD07839265622FDD5A720885A6245909981E07839ADD82E818D79
C4126C49C7739AFE62C41036E958C87EBB1E07835417C0CE3E2B8181911888B9
62FDD4241B88E20C8C2307CD54EBB1E4061888B962FDD07835417C0CEB49B599
8DD4D07B2311DCA33EBB9CE5A72E7589ADB2C488B2C07A68920903902E2DA7A6
8B5990532C285075320B65503FDD07A68B5990046C1C28F5EF4222127BE45246
22FDD5A77353CDAC4443BEC8FE62B79E9017589ADB2C4CFA03C9A16A042C4288
B4BE9A1E65624D80B061C5D80CA551CC773C9A1E6562009170B0E79F316E1358
03902E2D6C423617E2810028B3119036E2620CE894090693817B444E51B8C12E
698E038D50E698A60B655D1B65507A68B5990046C1C2832385E0DA2E98B4F4D0
7B231A6406DAA0E56007A68B5990532C285070016068AAC773C90169B3119036
E26A82E61C89050E4D07B231E4442C89B892A8B50362418353CDAC4008030345
5EBB1E4D07B23108C838507722216CC5C415C130BF8B52A4BB5839C85C9B0600
80EA60B655D1B655074C4C83624186126C49900C1E0E278C547405F946C2EC50
30040F866D91FDD46F2D312E2D35B79E98F5A78353CDAC4443350A050643BEC8
FE62B79E9017589ADB2C4CFA03C9A1E65624D80CA551CC773C9A1E6562004818
1AAE2308353CDAC40023E061C3A9576C7739DB2C488B2C4DE5162E7581E07831
6E135803902E2D6C423617E2810028B3119036E2620CE894090693817B444E51
B8C12E698E038D50E698A60B655D1B65507A68B5990046C1C2832385E0DA2E98
B4F4D07B23108C838507722216CC5C415C130BF8B52A4BB58353CDAC48A1185B
A287910C901D13522A345A262967B9BA62447C498825E2097261A878ABCF9016
9B3119036E26A82E61C89050E4D07B23108C83850F866D91FDD46FA031FB2C4D
E51624C5168353CDAC40080303455EBB1E4D07B231E4442C89B892A8B5036241
8353CDAC4443350A050643BEC8FE62B79E98F516A6FA0312EA03C946C2EC5030
04075385BAAE85BA28326291B8371C0001C3A9576C7739DB4F4CF2D35B79E901
79E1E4D07B231A6406DAA06EBB1E4D07B231A64850B0E002C0C0559FE68353CD
AC4008030345D5600726C131A04B0136AC400E0707934E2A328AF078F0
[=== Myrakalear-Mankrik profile ===]

**Comment by mech422** [comment]
oh - "players(10)" is the 'tank group' header

**Comment by michaelnpsp** [comment]
Unfortunatelly the role filter has some invalid codes stored in the profile that are not recognized in vanilla classic.
Deleting and Recreating the "Players(10)" header should fix the issue.
1. Take a screnshot or remember the Player(10) header settings.
2. Goto Players(10) header, scroll down and use de Delete button to remove this header (only this header will be deleted).
3. Click on "+" tab, create a new header and configure  all  header settings.
Now the role filter should work.

**Comment by mech422** [comment]
Thanks - will try that...

**Comment by mech422** [comment]
ok - did a quick check and thats seems to have fixed it.  :-D
Thanks very much for you help! And thanks for an awesome plugin 
(as a programmer - I was impressed with how clean the code is ! )
