### ISSUE TITLE
Question: Possible to create a buffs group that only triggers if ALL members are missing ?

### ISSUE THREAD

**Issue by mech422** [michaelnpsp/Grid2#168]
Hi!

I had a quick question - is it possible to create a buffs group which only triggers if ALL members are missing ?  For instance, can I create a buff group that triggers if BOTH gift of the wild and mark of the wild are missing from a unit ?  or say arcane brilliance and arcane intellect are missing from a unit ?  This would be very handy for buffs having both a 'group' and 'individual' version of the buff.
(We typically use group buffs at start of raid, but buff people individually if they are rezzed...)

Thanks Again!

**Comment by michaelnpsp** [comment]
This is the standard behaviour for "buffs groups" statuses.

**Comment by mech422** [comment]
Hmm - I'm specifically having problems with Gift of Wild or Mark of Wild on vanilla classic, with updated grid2 v2.3.22.  Ahh..I think I got it.  I was putting "Gift of the Wild, Mark of the Wild" in the name or spellid of the 'create' screen.  It should be in the 'display' field after you create the buffs group ? Seems to be working now - Thanks Again!
