### ISSUE TITLE
Focus/target frames don't respect rangealt

### ISSUE THREAD

**Issue by andre-dsm** [michaelnpsp/Grid2#170]
When using rangealt (like when using a secondary spec resto druid) the focus and targeting frames remain on the default range value.
It'd be nice to at least have the focus frame on rangealt or at least have the option to use it on rangealt.

I sometimes focus particular tanks/units when raid healing and having them alpha out as they've gone out of attack range reduces the useability of that frame.

**Comment by michaelnpsp** [comment]
I dont understand what you mean with "remain on default range value".
38 yards range cannot be tested on target and focus due to game restrictions (UnitInRange does not work on non grouped/raid units), so for focus and target frames the addon checks for 28 yards range instead of 38 yards.
You can use spell or heal range instead.

**Comment by andre-dsm** [comment]
> I dont understand what you mean with "remain on default range value".

Ah.. by default range value I mean "range" or "rangealt". When I am using "rangealt", grouped player units get set to the range set by "rangealt", however focus and target still seem stuck on "range".

> 38 yards range cannot be used on target and focus due to game restrictions (UnitInRange does not work on non grouped/raid  units), so for focus and target frames the addon checks for 28 yards range instead of 38 yards.

This kinda answers my question.. looks like its not possible, although I'm intrigued by your comment on using spell or heal range instead. Can these be used individually for focus and/or target?

**Comment by michaelnpsp** [comment]
In the Range configuration instead of selecting the number of yards you can select "spell range"  to setup a friendly and hostile spells to check the range against,.
Spells ranges can be checked against non grouped units like target or focus.
