### ISSUE TITLE
Amirdrassil Raid Debuffs Update

### ISSUE THREAD

**Issue by SamJin98** [michaelnpsp/Grid2#172]
Hey Michael,

With the new raid set to launch next week, do you know when the debuffs for Amirdrassil will be included in the Raid Debuffs section? I'm concerned that the local modifications I've made might get overwritten by the official update.

I've enjoyed using Grid2 for quite a while and I'm willing to lend a hand with the updates if needed.

**Comment by michaelnpsp** [comment]
Probably tomorrow or the next day.  I had no time yet to filter the spells list and remove non-aura spells.
If you have a more or less polished list of debuffs, you can export the raid debuffs an post here the data if you want.
You have to:
1. Goto "General/About" Tab and enable the "Grid2RaidDebuffs" toggle in the "Debug" section.
2. Goto Raiddebuffs configurattion, select "Dragonflight" module
3. Next to the Instance selection option , a new  combobox  called  "Develop" should be displayed.
4. Click on this "Develop" combox and select the first option "Gen Lua"  
5. A new window with the dragonflight instances and raid debuffs in text format should be displayed.
6. Now you can use Ctrl-C , Ctrl-V to copy/paste the debuffs data.

**Comment by michaelnpsp** [comment]
Update to version 2.4.1
