### ISSUE TITLE
Buffs missing on pets

### ISSUE THREAD

**Issue by sfjuocekr** [michaelnpsp/Grid2#182]
Pets do not show missing buffs, maybe I've overlooked something but most of these pets are not buffed and should show me a Power Word: Fortitude icon.

![image](https://github.com/michaelnpsp/Grid2/assets/398018/e7933030-eebd-4b0b-96e0-06038e001d62)

**Comment by michaelnpsp** [comment]
Missing buffs on pets are not displayed on purpose, because usually no one buff pets, and all of this icons will be useless and too distracting.

**Comment by sfjuocekr** [comment]
I might be an exception to the rule I guess, I'm also a faithful pet healer and usually the pets are taken care of with prayer of fortitude.

Could there be a checkbox to turn this behavior on or off?

**Comment by michaelnpsp** [comment]
Update to version 2.6.9-beta, now buffs statuses have an option to display missing buffs on pets.
