### ISSUE TITLE
[request] bleed debuff filtering?

### ISSUE THREAD

**Issue by SakuSSBM** [michaelnpsp/Grid2#183]
alo again :)

i'm not really sure if this is possible but could you add another debuff category for bleeds that automatically filters all bleed type debuffs in dungeons/raids? i've made my own bleed debuff category, but i have to search for and add all of the spells manually so this can be kinda annoying at times >.<

![image](https://github.com/michaelnpsp/Grid2/assets/102873344/9fe3bbb6-10ba-498f-9ffb-167a658f1561)

also off-topic; do you have an official discord server (for troubleshooting, quick guides etc.)? 
and is there any way to support you guys somehow? =)

**Comment by michaelnpsp** [comment]
Unfortunatelly the game does not have a "bleed" category, so there is no easy way to know if a debuff is a bleed or not. The only way is to manual make a list of debuffs.
Sorry there is no discord server. There is a little donate button nearr the download/install buttons in curseforge: 
https://legacy.curseforge.com/wow/addons/grid2

**Comment by SakuSSBM** [comment]
oh that's a bummer :/
but good to know, thank you ^-^
