### ISSUE TITLE
[request] allow spell id tracking on buff/debuff lists

### ISSUE THREAD

**Issue by vitor-f2f** [michaelnpsp/Grid2#184]
The option to track a buff or debuff by id instead of name exists for singular aura indicators, but for lists it automatically turns into the spell name and then tracks all auras with that name. My use case here is I'm trying to replicate bigdebuffs functionality where some debuffs are larger, specifically this will be CC and important dispels. Some of these spells apply multiple effects with the same name, like Rake has the bleed and the stun, The Hunt has a root and a dot, etc. Would be sick, ty.

**Comment by michaelnpsp** [comment]
Try out 2.6.11-beta version.
