### ISSUE TITLE
Add decimals to Percent Format

### ISSUE THREAD

**Issue by Heimidall** [michaelnpsp/Grid2#186]
I would like to know if it is possible to add decimals to the percentage text format.
I was looking for information but was not able to find anything about whether this is possible or not.

Thanks in advance
![image](https://github.com/michaelnpsp/Grid2/assets/18452593/6ef13b39-1511-44b1-89b2-0fb6a3835838)

**Comment by michaelnpsp** [comment]
Not possible using the standard configuration, but it's possible changing the format in the configuration, typing into chat something like:

-- 1 decimal
**/script Grid2.db.profile.formatting.percentFormat="%.1f%%"**

-- 2 decimals
**/script Grid2.db.profile.formatting.percentFormat="%.2f%%"**

--1 decimal,  and the percent symbol removed
**/script Grid2.db.profile.formatting.percentFormat="%.1f"**

**Comment by Heimidall** [comment]
Thanks! It worked
