### ISSUE TITLE
Load condition for when unit is alive only.

### ISSUE THREAD

**Issue by strickland** [michaelnpsp/Grid2#188]
Load options is in need for "Load if alive?" condition, I've had some statuses that shouldn't appear when dead but they're appearing, for example "Buff: shown if missing" then if you're dead the indicator will be up, even though I am dead. I was looking for "Load only if alive" but I couldn't find it. 

Similar I have border when "health-low", then if i'm dead the indicator is still shown as "low-health" even though i'm/party is dead.

**Comment by michaelnpsp** [comment]
Try out 2.6.12-beta version.

**Comment by strickland** [comment]
I've tried it, low-health border now is gone when I'm dead, but other stuff are still shown when I'm death...example now low-mana border and missing buffs show if i'm dead.

if you could just add one condition and let the user to decide if he wants to show it when dead or not would be perfect just like weakauras, "Condition name: Load only if alive?" but its up to you man.

**Comment by strickland** [comment]
Just for clarification, I've got low-health as red border, and low-mana as blue border....previously when someone is dead I see red border stay up because it had higher importance level in the grdi2 settings, however once that was fixed now I see the low-mana blue border after someone is dead. 

All I'm saying here is there may be some other indicators in grid2 that shouldnt appear on dead also, having the option to enable/disable them on death would be neat, if applicable.

**Comment by michaelnpsp** [comment]
Unit Load conditions can only by applied to buffs and debuffs (non-buff/debuff stauses have no unit load conditions). So i cannot implement this kind of load condition to mana or health statuses.
If you want to hide all border statuses when someone is dead simply assign a full transparent or black color to the "Death" status, and link this status to the border indicator (put the death status first in the list).

**Comment by strickland** [comment]
1) Yes please undo the health-low dead check because you're method is clear to have another border transparent & assign it to death. Its very good idea, why haven't I thought of doing it, ill do it now.

2) About the buff displayed on dead. Sorry I just found the Unit alive condition, and I've put it to Yes and its working perfectly. I didn't see this condition before maybe it was pushed in new release? or maybe I am blind :o haha, thanks.

**Comment by strickland** [comment]
I tried to assign transparent for dead status as border and make it transparent, the problem with this is that I also use text for dead status which says "GHOST" or "DEAD" for units, and if i make it transparent this status and put it on border, then the text also disappear. You know what ill leave the health-low border to stay up on dead people, what else to do :) no problem.

**Comment by michaelnpsp** [comment]
You can use a static color for the GHOST/DEAD text instead of the death status text color. 
Goto "Statuses/Colors" create a color status, and assign the new created color status to the text indicator.
Using static colors statuses to colorize indicators (when possible) is more efficient than using the colors provided by most statuses.

**Comment by strickland** [comment]
Thanks for the explanation, this is a beautiful idea and it worked very nicely & easily. Thanks for this....

You said u gona revert the change the remove the health-low alive check, but did you also remove the buff/debuff alive condition also? cause updating github removed that as well. I dont know if its intended or not.

**Comment by michaelnpsp** [comment]
Unit Alive condition remains, i only removed the  health-low alive check.
