### ISSUE TITLE
'players' Layout. Roles/Group section check/uncheck

### ISSUE THREAD

**Issue by GitNotus** [michaelnpsp/Grid2#190]
Since few releases , its not possible anymore to mix 'Named list' with party names frames .
Also, In the Roles or Group section , you can not  uncheck everything (its revert back to fully check)

**Comment by michaelnpsp** [comment]
Working as intended: It has no sense to uncheck everything: this means: display nothing.
I dont understand the namelist issue, party units and player names cannot be mixed in a name list, this thing never worked, the blizzard code used by grid2 does not support this.

**Comment by GitNotus** [comment]
Raid units to be precise. That way you would have multiple same name in one raid group or one name who was not belonging to a specific group in that group.(tank/healer on the far right/left) Unchecking was helping to made some column disappear .

**Comment by michaelnpsp** [comment]
I simply don't understand this issue at all, your are talking about things than never worked/were implemented in Grid2. 
There is no version of grid2 (old or new) that allow to mix raid units and player names in namelists. 
The same for the posbiility to unclick all groups/roles, this behaviour never existed.
