### ISSUE TITLE
[Bug ?] Indicators not showing on Timewalking Dungeon

### ISSUE THREAD

**Issue by Choupiyan** [michaelnpsp/Grid2#194]
Hey !

First, I'd like to thank you for your amazing work on this addon. Using it for years, really helpfull !

Second, I'm so sorry if that's been already asked, or if it's an obvious answer, but that drives me crazy. I've been serching for a long time now and I still don't get it : Grid2 is working on Timewalking Dungeon BUT there is no indicators working on it. I tried to search every options, I didn't find the answer.

So sorry to bother for that.

Cheers. 

Choupiyan

**Comment by michaelnpsp** [comment]
Which indicators ? Health bar, health text or the unit/player name are indicators too.

**Comment by michaelnpsp** [comment]
Did you check the load tab of the statuses ? Maybe buffs or debuffs are filtered there by instance type.
You can export and send me yor profile too (To export the profile to text format: General/Profiles/Import&Export).

**Comment by Choupiyan** [comment]
Oh ! I guess that was that ! 
I searched for weeks... >< Thank you very much, and sorry for the trouble :x
