### ISSUE TITLE
[BUG] Icons indicator cooldown swipe draws over stacks

### ISSUE THREAD

**Issue by jparac** [michaelnpsp/Grid2#195]
Hey, currently setting up fresh grid profile. I'm not sure if there is something I'm doing wrong, but cooldown swipe is being diplayed over stacks count ONLY  on `icons` indicator. It works as expected on `icon` indicator
![Screenshot 2024-01-13 150359](https://github.com/michaelnpsp/Grid2/assets/3684793/33751092-0336-4934-9278-574c2ed8f299)

**Comment by michaelnpsp** [comment]
Working as intended. Displaying the stacks on top requires creating a extra frame per icon, It was programmed in this wais to save resources.
