### ISSUE TITLE
Unit roles filter for classic

### ISSUE THREAD

**Issue by praxxis** [michaelnpsp/Grid2#196]
In classic the ["Unit Role" loader](https://github.com/michaelnpsp/Grid2/blob/4df40747b99f51e2297b31bbfda13ec76bbbccbb/Options/modules/statuses/Status.lua#L376-L383) doesn't have any effect, as the roles are loaded using an [API that doesn't exist in classic](https://github.com/michaelnpsp/Grid2/blob/4df40747b99f51e2297b31bbfda13ec76bbbccbb/GridCore.lua#L10). We could use the [raid role](https://wowpedia.fandom.com/wiki/API_GetRaidRosterInfo) to at least be able to support "Tank" and "Other" unit roles in classic (it's already used [elsewhere](https://github.com/michaelnpsp/Grid2/blob/4df40747b99f51e2297b31bbfda13ec76bbbccbb/GridGroupHeaders.lua#L152) in Grid2.)

I could PR this change if you're open to it too. I'd probably create a classic only `PLAYER_ROLES` in `modules\statuses\Status.lua` with just `Tank` and `None`, then somehow change `GridStatusLoad` to load the role from the raid index instead of unit identifier.

**Comment by michaelnpsp** [comment]
Im unsure about changing this behaviour because the Role API do exist in classic, only that currently is not used.
Anyway changing the GridStatusLoadCode is not necessary, Simply changing the Grid2.UnitGroupRolesAssigned() function should be enough.

**Comment by michaelnpsp** [comment]
Try out 2.7.1-beta-classic

**Comment by praxxis** [comment]
Just tested in raid and it looks good. The only issue I saw is that statuses don't get loaded if you set/unset a main tank until you reload or zone. Might be a cache or something not getting busted.

**Comment by michaelnpsp** [comment]
Umm, the required event to refresh the roles is not registered for classic. Unfortunatelly i cannot test this thing in classic era just now (i need to be in raid to test this thing).
Can you comment lines 151 and 152 in GridCore.lua to activate the RegisterEvent() function and test if this fixes the issue ? 

`	-- if self.versionCli>=30000 then -- wotlk or superior
		self:RegisterEvent("PLAYER_ROLES_ASSIGNED")
	-- end
`
I know the PLAYER_ROLES_ASSIGNED exists in classic but i dont know if it is fired when maintank is set.

**Comment by michaelnpsp** [comment]
Update to 2.7.2-beta

**Comment by praxxis** [comment]
2.7.2-beta works perfectly! Confirmed that indicators update when promoting/demoting without needing a reload
