### ISSUE TITLE
Not seeing "shields" and "shields-overflow" statuses in Classic SoD 1.15.0

### ISSUE THREAD

**Issue by k3rp** [michaelnpsp/Grid2#197]
Heya michaelnpsp!

I wanted to add the multi-bar configs for my priest absorb in Wow Classic but "shields" doesn't show up for me as an option under the "health" category. I'm on version 2.70.0.

I did notice that there is a lua file at `Grid2Options\modules\statuses\StatusShields.lua`
but didn't do any more digging that that. Do you think it's possible to get this to work in Wow Classic? 

Cheers, 

![no_shields](https://github.com/michaelnpsp/Grid2/assets/32847778/a258e813-aef8-464d-9046-7b172e7d7de8)

**Comment by michaelnpsp** [comment]
Shields are not available in SoD becaouse the required blizzard API to get the dataabout shields is disabled in classic versions.
