### ISSUE TITLE
Classic - Buff Duration Not Working On Other Players

### ISSUE THREAD

**Issue by EmElw** [michaelnpsp/Grid2#2]
Title. Duration info is present for the player. I assume LibClassicDurations is used, and other addons like WeakAuras and SUF can use it so that does not seem to be  the problem. Works fine for debuffs, although I believe the API is different.

**Comment by michaelnpsp** [comment]
Did you enable durations in: General / General Tab / Auras Section / Enable Aura Durations option ?

**Comment by EmElw** [comment]
My settings:
![bild](https://user-images.githubusercontent.com/21335029/103640564-827adc80-4f50-11eb-832d-d2ffc3dc4ca7.png)

What my frames show:
![bild](https://user-images.githubusercontent.com/21335029/103640723-d4bbfd80-4f50-11eb-9d88-1c3f11b0b325.png)

The left one is my own frame which displays duration correctly (currently have cooldown text hidden, using OmniCC), but does not work for other group members.

**Comment by michaelnpsp** [comment]
Can you confirm if the durations are displayed in another type of buff statuses ? You can create a single buff or the blizzard buffs  status to do the test.

**Comment by michaelnpsp** [comment]
Try out version 1.1.7-alpha-classic
https://www.wowace.com/projects/grid2/files/3159618

**Comment by EmElw** [comment]
Seems to work. Thanks for the help.
