### ISSUE TITLE
bug report - border of each grid gets thick black & the grid health itself gets smaller in size.

### ISSUE THREAD

**Issue by strickland** [michaelnpsp/Grid2#201]
Grid2 version - 2.7.3  (github latest)
Wow version - Classic SoD
Duplicate the issue (maybe?)

1- be in raid.
2- have "By Raid Size" many options for each 5+ increment players.
3- Be in combat while this happens...
4- while in combat & in that raid, if the raidleader invites somebody this problem will happen. where grid goes smaller in size but also the border around the healths of players will become thick and black.

To fix it, just reload ui.

The location I'm in when it happens is ashenvale battle. But yea mostly this is the only place where you'd be in combat and people will keep inviting players into the raid, such that it happened to me multiple times....

Thanks, ill try to capture a screenshot the next time it happens..now I dont have any

**Comment by michaelnpsp** [comment]
Update to version 2.7.9-beta. 
Keep in mind that raid size cannot be changed while in combat, so now any raid size change will be delayed until combat ends.
