### ISSUE TITLE
Add shields option to health-current without percent

### ISSUE THREAD

**Issue by Thormeister** [michaelnpsp/Grid2#202]
There is already an option for adding shields to health percent. I would love an option that adds shield to basic health aswell.
Example in image. My HP% is showing with shield but the total amount of HP is without the shield. Have the total amount of HP show with the shields.
![image](https://github.com/michaelnpsp/Grid2/assets/119768261/15558f9c-8452-4d2a-bf05-8be7b803ba84)

**Comment by michaelnpsp** [comment]
Update to version 2.8.1-beta
