### ISSUE TITLE
Question? Is it possible to show 1000k HP as 1m(million)

### ISSUE THREAD

**Issue by Thormeister** [michaelnpsp/Grid2#205]
Hey,
Just a question if it is possible to have an option to show 1000k HP as 1m?

**Comment by michaelnpsp** [comment]
This is a question or a feature request ?
There is no option to display 1000k hp as 1m. Usually players dont have so high health.

**Comment by Thormeister** [comment]
Was a question at first. but I would like to request it if it is possible.
Tanks usally haver over 1m and alot of players have over 1m hp wtih absorbs

**Comment by michaelnpsp** [comment]
Update to 2.8.5-beta, you must enable the option in health-current status configuration, and only works for health-current (not for health-deficit or heals).

**Comment by Thormeister** [comment]
Thank you
