### ISSUE TITLE
[Request] expanding grid2

### ISSUE THREAD

**Issue by Derpytickle** [michaelnpsp/Grid2#206]
I was wondering if it's been thought to expand grid2 for all unit frames, rather than just raid/party(which are fantastic btw, thank you). 

 It would be crazy awesome to have consistency between the frames appearance/functionality, which is something I'm finding that is lacking with both the standard wow frames and other ui addons like suf and pitbull. Much prefer grid2 and I would love to use it for all my frames. 

I did try fiddling/failing before asking, but I just might be dumb for missing something that I can do to actually achieve this on my own as the addon currently sits.

**Comment by michaelnpsp** [comment]
In General/Layouts/Layout tab you can enable frames for player/target/focus/targettarget/focustarget&bosses.
In General/Appearance/Layout Disposition you can setup different sizes for player/target/etc.
In the Load Tab of each indicator the Unit Type filter option can be used to enable indicators only for certain frame header types.

**Comment by Derpytickle** [comment]
Well alright then, so I am a bit dumb lol thank you for pointing me in the right direction, this makes me so happy!
