### ISSUE TITLE
SoD Rangecheck infight

### ISSUE THREAD

**Issue by kbinz** [michaelnpsp/Grid2#207]
I've noticed that the "Range" status is no longer functioning properly in-fight since phase 2.
It works totaly fine out-fight, but when I enter fight every playerframe is shown as it would be out-of-range.
I played with the loading conditions but nothing changed.

**Comment by michaelnpsp** [comment]
Update to 2.8.6-beta.
Report back if this fixed the issue (and which classes are you playing).

**Comment by michaelnpsp** [comment]
Yes, unfortunately blizzard restricted the posibility to check different ranges in combat, so now only the 40 yards range option is available. 
But it's not 40y, the real distance checked depends of the class and the game client.
