### ISSUE TITLE
current health fully shown

### ISSUE THREAD

**Issue by KisyaDD** [michaelnpsp/Grid2#210]
show the current health so instead of 849.8k you can turn it into 849810 for example, Thank You

**Comment by michaelnpsp** [comment]
In classic version you can enable raw numbers in health-current configuration. 
In retail is not available because the health numbers are too big. 
Do you really want to see those long numbers in retail ?

**Comment by KisyaDD** [comment]
if its possible to change the size of numbers then yeah

**Comment by KisyaDD** [comment]
> if its possible to change the size of numbers then yeah
 i've always liked seeing the full number more but if its too much I could get adjusted to the current state

**Comment by michaelnpsp** [comment]
Update to 2.8.9-beta version. 
Goto health-current status configuration and uncheck the "display thousand numbers" option.

**Comment by KisyaDD** [comment]
awesome, thankyou
