### ISSUE TITLE
Issue with readycheck

### ISSUE THREAD

**Issue by strickland** [michaelnpsp/Grid2#211]
I'm using latest beta version of grid2. I haven't posted this issue before to make sure it happens more than once, granted it haven't happened like more than 10 times or anything but to me it happened like 3-4 times and only way to fix it is to reload ui, but during fight its hard to reload ui so sometimes I'm stuck with those readycheck marks in the middle of my grid for the duration of the boss fight.

TLDR;

issue: readycheck marks the red X and green checkmark both are stuck and do not disappear, even after combat ends they will remain there....until I reload ui.

how to duplicate: I'm not entirely sure, but perhaps it happens if the raidleader make a "readycheck" then during the period of where some people havent clicked yes or no, maybe the boss is pulled...then this issue might happen...try to reproduce it this way to see if it happens.

**Comment by michaelnpsp** [comment]
I cannot reproduce this issue. 
A second ready check cannot be launched if the first readycheck was not finished. Grid2 clears the ready check marks when the game informs that the ready check has been finished, so it seems game glitched and simply did not send the required event.
As workaround you can goto to icon-center indicator configuration (or the icon where the ready check is displayed) and move down the ready check status to the bottom of the list, in this way the ready check mark dont cover another info like debuffs if a combat starts.

**Comment by michaelnpsp** [comment]
I added a toggle in ready check status configuration to hide the ready check icons if combat starts, this should alleviate this issue.
