### ISSUE TITLE
The nickname font is not loaded

### ISSUE THREAD

**Issue by ohryk** [michaelnpsp/Grid2#213]
Hi,

When `Fira Sans Condensed Medium` is selected as the default font - the nickname is not displayed after login. It can be fixed by running `/reload`.
<img width="532" alt="Screenshot 2024-03-11 at 18 33 46" src="https://github.com/michaelnpsp/Grid2/assets/77839198/3f713789-5c17-412b-8d97-c84fd8900ae6">

Probably this font is added to the shared media by WeakAura.

WoW version: SoD
Grid2 version: v2.8.8

**Comment by michaelnpsp** [comment]
This means the font is not available when Grid2 is enabled. You must register the font early. 
WeakAuras are not a good method to register a font, they are loaded later in the addons load&enable process.

**Comment by michaelnpsp** [comment]
Try out 2.8.11-beta version. Report back if this version fixed the issue.
Note for future reference:
Strange thing. Some fonts are not displayed on login if :SetFontObject() is used to assign some default font settings to the font string. It seems a different text must be assigned to the font string to "unstuck" the widget (calling SetText() twice and with different texts).

**Comment by ohryk** [comment]
Hi. I tried 2.8.11-beta version - it looks fine now. Thanks a lot!

PS. About your note - I noticed that in almost all addons some fonts are not displayed instantly when open the font combobox. There is a blank space instead and closing/opening this combobox fixes the issue. Probably it might be related.
