### ISSUE TITLE
Role sort in custom layout 

### ISSUE THREAD

**Issue by epicowo** [michaelnpsp/Grid2#216]
The "Sort by" tab doesn't have any options to sort by role, and if it's supposed to work with "Def.", it doesn't. Or "Group by" tab have only group or role sort, but doest have "By Group & Role" options. (Wotlk Classic and Retail, and dont work with MT OT sort as tanks in SoD)

![1](https://github.com/michaelnpsp/Grid2/assets/151256616/36f7e535-cb0b-4311-8b6c-a8c44eb33039)
![2](https://github.com/michaelnpsp/Grid2/assets/151256616/6e1db8c0-4df0-4735-a50d-c5d6076eb015)
![3](https://github.com/michaelnpsp/Grid2/assets/151256616/6f733a11-defa-4f93-ac1d-cc55c40d1c27)
![4](https://github.com/michaelnpsp/Grid2/assets/151256616/29296545-3fd6-4a77-8e2e-f96c40faa128)

**Comment by michaelnpsp** [comment]
Classic version don't support dungeon roles, so all related role sorting dont work.
