### ISSUE TITLE
Grid2 API points

### ISSUE THREAD

**Issue by guilliotine13** [michaelnpsp/Grid2#218]
Couldn't find a comment box under Curseforge or a Discord for Grid2, so apologies if this is the wrong place. 

I have been wondering if API points exist for Grid2. The use case would be to access/extract the frames after they have been sorted with the sorting that takes place within Grid2. This will be used to determine if Frame1 is "party3", the tank and if Frame2 is "party1", the healer and so on. Any way to fetch the current ordering of units, basically.

Thanks in advance!

Note: I have realized that the indicator for that exists as "unit-index". I'm more curious about fetching it through Lua.

**Comment by michaelnpsp** [comment]
SecureButton_GetUnit(SecureFrame) wow api function returns the current unit for the specified frame.

**Comment by guilliotine13** [comment]
Thank you so much for your detailed response!

I thought that sorting was handled internally by Grid2, did not realize that it was handled by Blizzard. I will look into the methods you have provided.

To clarify, I am going to use this in my own addon and was curious which frame represents which unit name/unit ID.

Once again, thanks for the response, love the addon and your work!
