### ISSUE TITLE
[TBC] LUA error while casting Flash Heal rank 8

### ISSUE THREAD

**Issue by bgatellier** [michaelnpsp/Grid2#22]
Hi,

I've got the following error when I try to cast [_Flash Heal rank 8_ (spellID 25233)](https://tbc.wowhead.com/spell=25233/flash-heal) on any _Grid2_ player frame, using the _Clicked_ addon.

As the error gives links to _Grid_ files, I think that the error is more related to the _Grid_ addon rather than the _Clicked_ one.

I am using Grid2 2.0.12-bcc

```
Message: ...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:758: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
Time: Fri Jun  4 20:40:57 2021
Count: 1
Stack: ...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:758: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@Interface\AddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:758: in function <...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:751>
[string "@Interface\AddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:1103: in function <...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1101>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:1993: in function `?'
[string "@Interface\AddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua"]:2446: in function <...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2442>

Locals: spellData = <table> {
 levels = <table> {
 }
 averages = <table> {
 }
 coeff = 0.428571
}
spellName = "Soins rapides"
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 62
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 62

```

**Comment by bgatellier** [comment]
As i describe this error, I think it is in fact an error in the LibHealComm library rather than Grid...

Sorry if it is the case

**Comment by Oritfred** [comment]
Hi, I have the exact same issue. All new ranks of spells causes this LUA error.

**Comment by moono999** [comment]
I have same issue with Rejuvenation.  When I reach level 64 and learned new Rejuvenation(level 12, spell=26981), the error pop out
17x ...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0-92.lua:758: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0-92.lua"]:758: in function <...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:751>
[string "@Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0-92.lua"]:829: in function <...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:827>
[string "@Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0-92.lua"]:1870: in function `?'
[string "@Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0-92.lua"]:2444: in function <...ddOns\Grid2\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2442>

Locals:
spellData = <table> {
 interval = 3
 levels = <table> {
 }
 averages = <table> {
 }
}
spellName = "Rejuvenation"
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 64
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 64

**Comment by michaelnpsp** [comment]
Update to 2.0.13-beta-bcc version:
https://www.wowace.com/projects/grid2/files/3318824
If this does not fix the problem, open an issue here:
https://github.com/Azilroka/LibHealComm-4.0/issues

**Comment by bgatellier** [comment]
Thanks for you quick answer.

Everything is working fine from my side, thanks a lot!
