### ISSUE TITLE
Debuff tooltip showing wrong spell

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#224]
I have only seen this happen in Algeth'ar Academy on Crawth, but when Sonic Vulnerability is on the frame and the tank gets hit by Savage Peck, If I hover over the Savage Peck debuff, the tooltip shows Sonic Vulnerability.

![Screenshot 2024-04-27 182622](https://github.com/michaelnpsp/Grid2/assets/20176169/a6363e3d-3f7d-45cc-a21c-fc17dcaa86de)

**Comment by michaelnpsp** [comment]
Which type of indicator and statuses are being used ? 
A single icon or a icons(plural) indicator. 
The debuffs are displayed using a raid-debuffs status, a group of debuffs status or several single debuffs statuses linked to the indicator ?

**Comment by martheli** [comment]
I use the icons indicator to show the raid-debuffs status.

**Comment by michaelnpsp** [comment]
Is the raid-debuffs "multiple icons support" option enabled?
Statuses >Debuffs > Raid Debuffs > General Settings > Raid Debuffs > multiple icons support

**Comment by martheli** [comment]
yes that is enabled

**Comment by michaelnpsp** [comment]
Update to 2.8.20 version.

**Comment by martheli** [comment]
fixed
