### ISSUE TITLE
Add player role to load condition

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#225]
Would be nice to have player role added as an option to load statuses:

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/fffde8b0-5f43-485c-bddb-9f398f88c74a)

I only want the frame to turn red if a player gets a magic debuff if I am playing a healer.

**Comment by michaelnpsp** [comment]
What about using the "Player Class&Spec" option ? Simply selecting the healing specs.
Another posibility is to create a "dispellable debufffs" group status, in this way only debuffs your class can dispell will be displayed.

**Comment by martheli** [comment]
I don't see a debuff status called dispellable debuffs

**Comment by michaelnpsp** [comment]
You have to create a group of debuffs.
1. Debuffs/Right Panel
2. Select "Debuffs" (plural)
3. Type a descriptive name for the status, for example "Dispellable" or "Dispellable-Debuffs" or wherever, and click the create button.
4. Goto the new status settings in the debuffs list.
5. By default all debuffs are displayed but in the display section there are a lot of filters.
6. Simply uncheck the  "Non Dispellable by Me" option.
7. Link the status to the desired indicator.

**Comment by martheli** [comment]
ahh ok cool that works
