### ISSUE TITLE
Feature Request - Simplify spell options from raid debuffs menu

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#226]
Alot of other party frame addons allow you to show/hide debuffs and then in the same window allow you to check whether you want the frame to glow when player has debuff. It would be nice if on this window:

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/b2d287a2-da20-48da-b8b8-f5ea5f9a0f57)

there could be some simple options to check like whether or not I want the frame to glow instead of having to copy the debuff to another window and then have to manage the debuff from two different pages.

**Comment by michaelnpsp** [comment]
Statuses are independent of the indicators so i cannot simpley add a glow option, because this means nothing for a status, even  several glow indicators can be created to display different statuses.
But you can classify the raid-debuffs, up to 5 raid debuffs statuses can be create, raid-debuffs1, raid-debuffs2, raid-buffs3, etc.
For example you can use "raid-debuffs " for normal debuffs, and "raid-debuffs2" for important debuffs that should be highlighted.
Then link raid-debuffs2 to your glow indicator.

**Comment by martheli** [comment]
how do you create a second raid debuff status group? Would I then have to uncheck all the debuffs and only check the ones that I wanted to glow?

**Comment by michaelnpsp** [comment]
In the "Raid debuffs" configuration window click on the second tab "General Settings", and click the "New" button, raid-debuffs(2) should be created.
By default the "Assigned to" option of each raid debuff  is assigned to "raid-debuffs" status but you can change this the option to "raid debuffs(2)". So simply move the important/glowing debuffs to "raid-debuffs(2)".
Then link the raid-debuffs(2) status to your glow indicator.
But If you want to display the icons of these second debuffs group, you must link the raid-debuffs(2) status to the same icon/icons indicator than "raid-debuffs" too.

**Comment by martheli** [comment]
I created a new raid debuffs status:
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/eb881b44-1df6-4144-b626-6aacd826f032)

When I go to assign it, it shows the old one as Raid Debuffs(1) even though that isn't what it's called. Then after it's assigned, the buff now has a (2) next to it:
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/8b28d8a9-99ba-4b38-a20e-602d17757ac3)

Are these numbers correct?

**Comment by michaelnpsp** [comment]
The number simply represent the statuses creation order (this number is really not part of the debuff name), is a fast way to know in the debuffs list which status is assigned to each debuff without clicking in all debufs one by one to inspect the "Assigned to" option.
