### ISSUE TITLE
Cataclysm Classic Issues/Lua Errors

### ISSUE THREAD

**Issue by joshlathery** [michaelnpsp/Grid2#227]
Health values are not updating and any health changes result in the following error

Message: FontString:SetText(): Font not set
Lua Taint: Grid2
Time: Tue Apr 30 20:37:38 2024
Count: 126
Stack: FontString:SetText(): Font not set
Lua Taint: Grid2

Locals:

**Comment by joshlathery** [comment]
Message: Interface/AddOns/Grid2/modules/IndicatorText.lua:128: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
Time: Tue Apr 30 20:47:10 2024
Count: 1
Stack: Interface/AddOns/Grid2/modules/IndicatorText.lua:128: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "@Interface/AddOns/Grid2/GridLayout.lua"]:722: in function `ForceFramesCreation'
[string "@Interface/AddOns/Grid2/GridLayout.lua"]:709: in function `FixHeaderAttributes'
[string "@Interface/AddOns/Grid2/GridLayout.lua"]:591: in function `AddHeader'
[string "@Interface/AddOns/Grid2/GridLayout.lua"]:561: in function `LoadLayout'
[string "@Interface/AddOns/Grid2/GridLayout.lua"]:538: in function `ReloadLayout'
[string "@Interface/AddOns/Grid2/GridLayout.lua"]:292: in function `?'
[string "@Interface/AddOns/GatherMate2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...te2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/GatherMate2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...te2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/GatherMate2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/Grid2/GridRoster.lua"]:403: in function `GroupChanged'
[string "@Interface/AddOns/Grid2/GridRoster.lua"]:338: in function `?'
[string "@Interface/AddOns/GatherMate2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...te2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/GatherMate2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...te2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/GatherMate2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/GatherMate2/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ddOns/GatherMate2/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 layoutSettings = <table> {
 }
 UpdateMenu = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:340
 PlaceHeaders = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:472
 EnableModule = <function> defined @Interface/AddOns/GatherMate2/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 baseName = "Grid2"
 Grid_GroupTypeChanged = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:289
 FixLayoutsTable = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:1127
 groupsUsed = <table> {
 }
 relativePoints = <table> {
 }
 UpdateColor = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:827
 UpdateHeaders = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:509
 UpdateTheme = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:266
 AddHeader = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:577
 UnregisterMessage = <function> defined @Interface/AddOns/GatherMate2/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 layoutName = "By Class w/Pets"
 instMaxGroup = 1
 groupsFilters = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/GatherMate2/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SavePosition = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:854
 GetFramePosition = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:984
 customDefaults = <table> {
 }
 defaultModuleState = true
 Grid_RosterUpdate = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:300
 IsEnabled = <function> defined @Interface/AddOns/GatherMate2/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 instMaxPlayers = 1
 UpdateTextures = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:818
 DisableModule = <function> defined @Interface/AddOns/GatherMate2/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 UpdateVisibility = <function> defined @Interface/AddOns/Grid2/GridLayout.lua:839
 instType = "none"
 partyType = "solo"
 RestorePositio

**Comment by michaelnpsp** [comment]
Update to 2.8.20-cata version

**Comment by joshlathery** [comment]
Thanks for the quick update
