### ISSUE TITLE
[TBC] Indicator for buff group status always displayed, even if "display if missing" is checked

### ISSUE THREAD

**Issue by bgatellier** [michaelnpsp/Grid2#23]
Hi,

I have a buff group status for 2 the two fortitude buffs : _Prayer of Fortitude_ and _Improved Power Word: Fortitude_ (_Prière de robustesse_ and _Mot de pouvoir : Robustesse amélioré_ in my french game client).

I set one buff name per line in the "display" text area:
```
Prière de robustesse
Mot de pouvoir : Robustesse
```

This group has the "display if missing" checkbox checked.

I have an indicator to display the icon on the group/raid frames.

What goes wrong:
The icon of the first buff is always the one displayed in the indicator (and that is not a problem), but it goes away only if I use this specific buff, and not the other one.

At classic, the icon disappeared whatever the type of buff, but since TBC, it goes away only if the buff of the first line is applied on the target

**Comment by michaelnpsp** [comment]
Working fine here, which grid2 version are you using ?

**Comment by bgatellier** [comment]
> Working fine here, which grid2 version are you using ?

I was using 2.0.12-bcc, but still appears with latest 2.0.14-bcc

Here are some screenshots of my configuration:

Status:
![WoWScrnShot_060621_131145](https://user-images.githubusercontent.com/1890804/120935078-5b902480-c701-11eb-9342-6289b90ce612.jpg)

Indicator:
![WoWScrnShot_060621_131236](https://user-images.githubusercontent.com/1890804/120935092-6945aa00-c701-11eb-8a82-3ba6c02e87c4.jpg)

**Comment by bgatellier** [comment]
Hi,

I tried to delete and re-create the indicator, with or without spell ranks and it works again (without spell rank).

Everything is working now as expected, si I'm closing this issue
