### ISSUE TITLE
SoD - Debuff duplication on debuffs blacklist.

### ISSUE THREAD

**Issue by Brae22** [michaelnpsp/Grid2#230]
Trying to blacklist[ this debuff ](https://www.wowhead.com/classic/spell=439958/kill-maim-bleed) but now everytime I add something new a weird duplication happens. https://imgur.com/JT2xr0L

If you want to check the profile [here you have it](https://github.com/Brae22/brae22wow/blob/main/Wotlk/grid2_BraeSODPhase3.txt). Statuses>Debuffs>ignored-debuffs-bottomleft

**Comment by michaelnpsp** [comment]
The comma sign is used to separate spells, so in the editbox you can write one spell per line or several spells spearated by commas in one line. Spell names with commas inside are not common, i have to see if i can fix this without removing the posibility to use commas as separators.

**Comment by michaelnpsp** [comment]
Fixed in version 2.8.22
