### ISSUE TITLE
[Feature request] Default profile when first using the addon

### ISSUE THREAD

**Issue by holypalaswe** [michaelnpsp/Grid2#232]
Most addon I use, have the profile called "Default" loaded when first logging in on a new character. Grid2 uses characterspecific profiles, where you manually have to change profile every time on a new character. With the themes feature, and load conditions for the indicators, status groups etc having different classes with same profile is fine now. I feel like making changes on all profiles for all characters when there are new patches or expansion is not really viable.

Is this something you'd be able to change? :)

**Comment by michaelnpsp** [comment]
Unfortunatelly themes an load conditions are rarelly used, so i think is not a good idea to change the default behaviour. Maybe an option in Profiles section to select a default profile ? In this way yoy only have to select a default profile for the this first toon created.

**Comment by michaelnpsp** [comment]
Added a default profile option in version 2.8.22
