### ISSUE TITLE
Summon Icon stuck

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#233]
Like the res icon, the summon icon gets stuck on the player even after they have summoned

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/2682e883-dd29-446b-828b-46e08719fd46)

**Comment by michaelnpsp** [comment]
It seems like the player did not accept the summon. To test this posibility next time do a reload ui, if the icon did not disappear this means  there is a pending report summon.

**Comment by martheli** [comment]
i see it happening with my friend as well. I accepted a summon and his frame still shows the summon icon for me

**Comment by michaelnpsp** [comment]
I cannot fix this issue, the status only has 3 relevant and very simle lines of code, probably a game bug/glitch.

**Comment by martheli** [comment]
reloading the ui fixed the issue, so might be a blizzard issue I guess then.
