### ISSUE TITLE
[Request] heal-absorbs for Cataclysm

### ISSUE THREAD

**Issue by gonstr** [michaelnpsp/Grid2#235]
Hey!

In Cataclysm, it would be really handy to be able to see absorb values in the raid frames.

I know this only works for retail and I think the reason is that `UnitGetTotalHealAbsorbs` doesnt exist until MoP?

https://github.com/michaelnpsp/Grid2/blob/fc228938a9a6a6121b9a6018eef109799b8e0266/modules/StatusHealAbsorbs.lua#L2

I was playing around with WeakAuras trying to make something similar and what I do know is that in Cataclysm absorb values show correctly in buff tooltips. I was able to make a WA quite quickly that would update some bars based on the tooltip of Power Word: Shield, Divine Aegis and Illuminated Healing (which I think are the 3 main absorbs).

Would it be possible to add support for heal-absorb in to Cataclysm using tooltip data or some other approach? 🤔

**Comment by gonstr** [comment]
Made a WA that enables the `shields` and `shields-overflow` statuses in Cataclysm: https://wago.io/Ba3YpVv6A

It's more or less the code from `StatusShields.lua` with some slight modifications to get data from the WeakAura triggers instead of native events that don't exist in Cataclysm.

The WA reads tooltip data of `Power Word: Shield`, `Divine Aegies` and `Illuminated Healing` to get absorb values.

**Comment by michaelnpsp** [comment]
Im not going to implement things based on parsing tooltips, its too resource intensive. But it seems UnitAura() is returning the shield values, at least for mages ice barrier.
Unfortunatelly i dont have a high level priest in cataclysm so i cannot gather the information for priest auras,  auras api returns up 3 custom values in the points[] array, i need to now the array index for the shield amount.
Maybef you can paste into your chat this code, and copy here the information printed into chat. You priest must have the shields auras active to gather the information about the auras.

`/script for i=1,40 do local d = C_UnitAuras.GetAuraDataByIndex("player",i); if d then print(d.name,unpack(d.points)) end; end`

**Comment by tabu14** [comment]
Hi, i run the script on my priest:
Power Word: Shield 14130 
Divine Aegis 1229

I also run it on holy pala for Illuminated Healing
Illuminated Healing 12067

**Comment by gonstr** [comment]
Yes, can confirm that shows the absorbs correctly. I also tried it on DK Blood Shield and it works too.

![absorbs](https://github.com/michaelnpsp/Grid2/assets/1374839/d441cd77-dc57-4035-b81a-a856e133bfc0)

Here are spell ids:

* Power Word: Shield `17`
* Divine Aegis `47753`
* Illuminated Healing `86273`
* Blood Shield `77535`

**Comment by gonstr** [comment]
DKs have [Blood Shield](https://www.wowhead.com/cata/spell=77535/blood-shield) but it only absorbs physical damage so I'm not sure it makes sense to track it.

![bloodshield](https://github.com/michaelnpsp/Grid2/assets/1374839/858256c2-8775-450a-bb99-d95e11e6fe11)

**Comment by michaelnpsp** [comment]
Try out 2.8.27-beta-cata version.

**Comment by gonstr** [comment]
Thanks for the quick work. Seems to work well! I deleted the WA.

**Comment by gonstr** [comment]
Tested in raid. Found no issues 👍 Think we can close this

**Comment by shambles1213** [comment]
Could you please add a feature similar to retail, where the 'current-health' status includes the option to 'add shield to health percent'?

**Comment by michaelnpsp** [comment]
> Could you please add a feature similar to retail, where the 'current-health' status includes the option to 'add shield to health percent'?

Try out 2.8.28-beta version.

**Comment by shambles1213** [comment]
awesome, thankyou

**Comment by gonstr** [comment]
One more absorb:

[96263](https://www.wowhead.com/cata/spell=96263/sacred-shield)

![absorb-sc](https://github.com/michaelnpsp/Grid2/assets/1374839/f3eabc00-37fa-424c-a677-c96d068b7aa8)

Shield value is first value in array again

**Comment by gonstr** [comment]
And a few more:

* [Feral Druid Savage Defense](https://www.wowhead.com/cata/spell=62606/savage-defense)

Savage defense only absorbs `physical damage` similar to dks blood shield

![absorb-sd](https://github.com/michaelnpsp/Grid2/assets/1374839/58d946cb-3bee-43b5-ac50-b52f0be1bb78)

* [Prot Pala Guarded By
![absorb-gl](https://github.com/michaelnpsp/Grid2/assets/1374839/96fd0729-778b-4d7d-b8ab-0e293f9bf4ca)
 the Light](https://www.wowhead.com/cata/spell=88063/guarded-by-the-light)

**Comment by gonstr** [comment]
That's really cool. Nice with a different color for physical shields 👍 

I think it would be nice with at least Sacred Shield and Guarded by the Light added to the list of tracked shields though:

```lua
local shield_spells = {
	[1463]  = 1, -- Mana Shield (Mage)
	[11426] = 1, -- Ice Barrier (Mage)
	[17]    = 1, -- Power Word: Shield (Priest)
	[47753] = 1, -- Divine Aegis (Priest)
	[86273] = 1, -- Iluminated Healing (Paladin)
	[96263] = 1, -- Sacred Shield (Paladin)
	[88063] = 1, -- Guarded by the Light (Paladin)
	-- [77535] = 1, -- Blood Shield (DK)
}
```

They are not physical only afaik and `C_UnitAuras.GetAuraDataByIndex` return the shield values for them

**Comment by michaelnpsp** [comment]
I think I have been misunderstood, i already added those new non-physical shields (but not published yet). In my previous post i was only talking about the druid and dk shields, not the paladin shields.
