### ISSUE TITLE
Is it possible to enable pings on frames?

### ISSUE THREAD

**Issue by drnoonien** [michaelnpsp/Grid2#236]
As far as I'm aware, it's currently not possible to ping the Grid2 unit frames, is this something that can be added?

Ref: https://warcraft.wiki.gg/wiki/Patch_10.1.7/API_changes#Ping_system

**Comment by michaelnpsp** [comment]
Try out version 2.8.25-beta

**Comment by drnoonien** [comment]
Works great, thanks!
