### ISSUE TITLE
[SoD] Instance Name/ID not working properly.

### ISSUE THREAD

**Issue by Brae22** [michaelnpsp/Grid2#239]
Tried several times and I reproduced this issue every time. Maybe is unique to Sunken Temple for some reason but it's the first time I have issues with this load condition. 

After entering Sunken Temple raid in Season of Discovery the statuses using the load condition Instance name/ID doesn't work until /reload is done or condition is unchecked and checked again.

Also noticed while doing these recordings that some other statuses with load condition set to Eastern Kindgoms/Kalimdor were still loaded inside Sunken Temple until I did /reload.

Didn't test in BFD or Gnomeregan and maybe will have problems in the future if blizzard decides to change any other dungeon into a raid.

[Proof here.](https://www.youtube.com/watch?v=IkTNBzPszr0)

[Proof #2](https://www.youtube.com/watch?v=auIv8hnuIlc) (doing normal entrance route from Swamp of Sorrows)

**Comment by michaelnpsp** [comment]
It seems in SoD blizzardd developers forgot to fire some important events in the new raids.
Try out  2.8.32-beta-classic version.
