### ISSUE TITLE
[TBC] Square indicator blink threshold doesn't work with stacks count

### ISSUE THREAD

**Issue by wibru** [michaelnpsp/Grid2#24]
Hi,
I created a square indicator for lifebloom showing different colours depending of number of stacks. It works.
I tried to add a blink threshold to have the indicator blink 2s before lifebloom fade. When I do that, only the first color is displayed despite the number of stacks (1,2,3), but the blinking threshold works.

It seems that I can't use multiple colors to track number of stacks AND have a blink threshold.

Do you have some clue (missconfiguration or real bug) ?
Thanks

Grid2 2.0.14 (2021-06-04), WoW BCC

Edit:
As a workaround, I managed to have what I want by creating 3 indicators on the same location with different priorities, and 3 lifebloom buffs customized to be displayed only with 1, 2 or 3 stacks.

**Comment by wibru** [comment]
![doesnt_work](https://user-images.githubusercontent.com/26368954/121006149-dd7b5e80-c790-11eb-9b9d-b2ec5188768e.png)
![works](https://user-images.githubusercontent.com/26368954/121006178-e409d600-c790-11eb-836a-e6b6ef01d9bd.png)

**Comment by michaelnpsp** [comment]
Simply Blink effect and colorizing by stacks are incompatible features that cannot by enabled at the same time.
In a future version i will hide the blink threshold option in the configuration to avoid confusion.

**Comment by wibru** [comment]
thanks for your answer!
