### ISSUE TITLE
When a death occurs, effective heal does not reset timely (sometimes)

### ISSUE THREAD

**Issue by thisisu** [michaelnpsp/Grid2#240]
Hi, after the update today in v2.8.30 I am often getting inaccurate displays of health-deficit. Often, when a player dies in a dungeon or a full wipe occurs, players that have resurrected will not show their health-current status until topped off again. Was something changed in health bc I don't see it documented? Please review the following screenshots for more context"

![WoWScrnShot_052024_230909](https://github.com/michaelnpsp/Grid2/assets/35790653/c9842f9f-2c2f-4bf6-861e-6bb1e4ad1ea2)
![WoWScrnShot_052024_225440](https://github.com/michaelnpsp/Grid2/assets/35790653/6aa4fc72-a565-4c7d-984e-958eb9ceff92)

I'm going to revert to the previous version until this gets fixed but just wanted to document the issue.
Thanks for your work! :)

**Comment by thisisu** [comment]
In case you need my profile to replicate, it can be found here: https://github.com/thisisu/grid2

**Comment by martin7125** [comment]
Having this issue too with health-current status. Occurs after every death. My profile can be found here if you need it: https://pastebin.com/G5s2HGJN

**Comment by michaelnpsp** [comment]
Verify the addon was really updated to the correct version , check the version in the about tab for example.
