### ISSUE TITLE
Feature Request - Improve ways to move frames

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#241]
I mentioned this a while back but I think it's worth bringing up again. Every single raid frame addon allows you to drag the frames by clicking on the frame and moving them around. There's no way a new user of grid2 is going to know they have to set a transparent border in order to drag the frames around.

As long as this option is set to false, you should be able to drag the frames around by clicking anywhere on the frame.
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/b05b4120-c52e-479c-818c-c22abcd61ef4)

**Comment by michaelnpsp** [comment]
The feature requested  can conflict with Clique, so i cannot implement this.
But in version 2.8.36-beta the frames can be fully draged when layout test mode is enabled, and i added a new test button in main options frame to easy enable layout test mode.
