### ISSUE TITLE
Feature Request - Show Current Health Percent

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#242]
On this options page for current health status, would be good to add a checkbox to show current health as a percent:

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/682cd018-33c0-4df7-8ec2-4d43704f84b6)

**Comment by michaelnpsp** [comment]
The percent display is controlled by the indicators settings. Goto the text indicator settings and and check the "Show Percent" option.
