### ISSUE TITLE
Coloring based on elapsed time flickering ?

### ISSUE THREAD

**Issue by holypalaswe** [michaelnpsp/Grid2#247]
Can be seen here: <https://www.twitch.tv/videos/2181134172?t=6h45m44s> on the shaman and warrior in bottom group. Happens every time the debuff is allowed to stay on the target for a longer time.
This is the first time I am having this issue after using similiar settings on other buffs/debuffs. Is it some weird interaction specifically with the Wrack debuff perhaps?

The settings I use for this status:
![image](https://github.com/michaelnpsp/Grid2/assets/29150498/3487e1fb-5e17-4038-99f8-31f346afcfd4)
and use it on the health-colors indicator:
![image](https://github.com/michaelnpsp/Grid2/assets/29150498/8c5325b0-cd94-4190-a8d4-7fecc1ef2f6e)

**Comment by holypalaswe** [comment]
I noticed you can also see it on the text-indicator in the bottomright, which has the status Sinestra>Wrack, which is identical to the one above except it turns green <15sec elapsed. And it so happens that the same time the health color flickers, that textindicator turns green for a split second.

**Comment by michaelnpsp** [comment]
That flicker happens when a buff/debuff is refreshed. For example every time the expiration time or number of stacks change. It was working in this way from day one, more than ten years ago.

**Comment by holypalaswe** [comment]
Yeah, the debuff Wrack ticks for more dmg every times it ticks, so I guess something happens for the split second after a tick when it is updating the dmg it does (tooltip changing perhaps?). Because the elapsed time (the text on bottomright corner) remains the same. [<https://i.imgur.com/DHgXt9g.mp4>](https://i.imgur.com/DHgXt9g.mp4)
