### ISSUE TITLE
TBC Weird behaviors with pet frame

### ISSUE THREAD

**Issue by joseph3114** [michaelnpsp/Grid2#25]
The pet frame loses interactivity when there are >1 pet present. Pets after the first appear, but can't be interacted with, ex mouseover, target.

When a hunter rezzes a pet or summons in combat the frame stays at 0 hp and black.

**Comment by Zwyk** [comment]
Can confirm the issue, seems to happen every time a new pet appear (summoned, ...)
Reloading or simply detaching-reattaching the pet frames fixes the issue (until it happens again).
