### ISSUE TITLE
Tooltip rollover area on icon does not move with icon if it is placed outside of respective unit frame?

### ISSUE THREAD

**Issue by c3pomagneto** [michaelnpsp/Grid2#251]
hi,

i hope i could describe the issue ;).

thanks for any suggestions

**Comment by michaelnpsp** [comment]
Tooltips simply dont work if the icon is placed outside of the unit frame area, its is designed/coded in this way.

**Comment by c3pomagneto** [comment]
cheers, thanks for clearing that up!
