### ISSUE TITLE
Raid-Debuffs->Option: Multiple Icons Support vs Indicators->Option: Icons or Icon

### ISSUE THREAD

**Issue by c3pomagneto** [michaelnpsp/Grid2#253]
hi,
i was wondering which Indicator to select when using Raid-Debuffs Status, as the option within Raid-Debuffs already has a multiple icon Support? or is it a case of enabling raid debuffs to basically print all debuffs instead of picking the respective one highest within the list and let the icons-indicator do the work?

thanks

**Comment by michaelnpsp** [comment]
For single icon indicators, the multiple icon option does nothing.
For icons (plural) indicators:
1. Multipe icons support enabled: All active raid debuffs are displayed in the the icons indicator.
2. Without multiple icons support: only one raid debuff is displayed (the one with highest priority), like with single icon indicators.

**Comment by c3pomagneto** [comment]
thank you so much for clearing that up!
