### ISSUE TITLE
help me for finding issues for the pkgmeta

### ISSUE THREAD

**Issue by trcrsired** [michaelnpsp/Grid2#255]
https://github.com/trcrsired/LookingForGroup/blob/master/.pkgmeta

I don't know why the .pkgmeta suddenly does not work for me on curse. It does not move folders any more but just delete the folders.

**Comment by michaelnpsp** [comment]
Umm, i think this issue does not belong here, and im not expert in pkgmeta format, but you can try adding a newline to the end of file.
