### ISSUE TITLE
New Feature - Shields and Overflow-Shields

### ISSUE THREAD

**Issue by LucasFrank** [michaelnpsp/Grid2#256]
Hi, is there anything you can do, if possible, to implement a way to manage shields and overflow-shields bar size, so it would not cover the entire health bar when the shield is too big?

If you can, it would be much appreciated.
thank you

**Comment by michaelnpsp** [comment]
I dont unsderstand how you want to display the shields, you can use an extra small bar for shields, or use a line instead a bar to represent the shields-overflow ?

**Comment by LucasFrank** [comment]
Sorry if i wasn't clear, i meant when we attach the shields and shields-overflow to the health bar, just like in the screenshot below.
![shield-overflow](https://github.com/user-attachments/assets/cdf0c5f2-5de9-45c5-8a3f-e799631bc70e)
In this screenshot, the shields-overflow is a bar that is attach in the right side and grows to the left side.
Many people enjoy using it like this because it is easier to see if someone has a shield, but sometimes if the shield is bigger enough, it would cover the whole frame and we would not be able to see the players health bar under it clearly. So if there is a way of managing this bar size according to the shields and shields-overflow values, it would be amazing.

Thank you again.

**Comment by michaelnpsp** [comment]
Use a multibar indicator to display the health bar and shields, and configure the indicator to display a  shield bar growing to the rigth  just next to the bar health.
For the overflow, the multibar indicator can display glowing lines, or you can attach  a overflow-shields bar to the health bar and make the bar grow to the left.
There is many ifferent ways to display that bars,  It's a matter of taste to use one way or another.
The multibar section in this guide explains howto setup different stacked bars to display health, heals and or shields, it does not cover the glowing lines because this option is new in the multibar indicator.
https://michaelnpsp.github.io/grid2-murloc-guide/

**Comment by LucasFrank** [comment]
The thing is I am already using multibar for it, the problem is that sometimes the shield bar gets too big and i would like it to be smaller.
About the overflow, i haven't tried this glowing lines option yet, I am going to test it first, currently I am using the second option you said, but if the player gets a lot of shields while being full health or close to it, the overflow bar can take almost the entire health bar, and since i use the health bar for tracking some buffs (Ex: if i have rejuvenation on a player, i color his health bar ), it sometimes can be annoying.

Thank you for your time.

**Comment by michaelnpsp** [comment]
I really dont understand the request, if the shield is big, then is big, what do you want ?, To display a wrong shield value if the shield is bigger that some some amount ?

Maybe use a more transparent color for the shield, or use a different small bar at the top or bottom not covering the health bar (like a mana bar but to display the shields).

Or use a different setup like displaying the shield covering only the missing health part of the bar and growing to the right, in this way the shield never covers anything important, and really that is the logical placement for the shield, i really dont understand the logic on displaying the shield starting at the right side of the frame and growing to the left.

```
|-------------------------------- max-health---------------------------------------------------|
|=== health ======>------- shields --------->______________Missing health__________________|
```

**Comment by LucasFrank** [comment]
I see, i'm going to take a look at it.

Thank you for your time anyway, i really appreaciated.
