### ISSUE TITLE
[DF] When Frames are hidden (solo, Layout = None) A small part of the background is still displayed.

### ISSUE THREAD

**Issue by Mongrul** [michaelnpsp/Grid2#257]
Since prepatch I cannot get this small box to go away. Adjusting any settings in the Look and Feel tab will make it go away temporarily, but it reappears when the Grid2 Options window is closed. I think this used to be a thing if the frames werent locked, but that does not make the tiny box go away.  It seems like it is a small part of the Background Texture that still remains. 
![smallbox](https://github.com/user-attachments/assets/02bcc3c8-395e-498f-aeeb-ea9fba741775)
![FrameDisplayed](https://github.com/user-attachments/assets/47a729a9-0507-4dbe-bb38-70bdd9b36834)

**Comment by michaelnpsp** [comment]
Really "none" layout means: display no units, and the frame decoration is independent.
There is an extra option to hide the background and border in: 

1. General/Appearance/Layout Look&Feel
2. Show Frame option, you can select: None, Always, Grouped or Raid.

**Comment by Mongrul** [comment]
Show Frame = Grouped was the answer and got rid if that little box when solo.  I appreciate it!
