### ISSUE TITLE
Hide Blizzard Frames not working

### ISSUE THREAD

**Issue by mp-regenii** [michaelnpsp/Grid2#260]
Hi, none of the "Hide Blizzard Frames" are working anymore since the last patch.

Bugsack:
63x Grid2Options/modules/general/GridGeneral.lua:320: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@Grid2Options/modules/general/GridGeneral.lua"]:320: in function <Grid2Options/modules/general/GridGeneral.lua:316>
[string "@Grid2Options/modules/general/GridGeneral.lua"]:348: in function <Grid2Options/modules/general/GridGeneral.lua:348>
[string "=[C]"]: ?
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:839: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:661>
[string "=[C]"]: ?
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...ue/Libs/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

Locals:
k = "raid"
v = true
(*temporary) = nil
(*temporary) = "Blizzard_CompactRaidFrames"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

**Comment by michaelnpsp** [comment]
Fixed in version 2.8.44
