### ISSUE TITLE
Feature Request - Cooldown Updates

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#264]
In indicator cooldown section, would be good if there was an option to hide the swipe and another option to only show the remaining duration on auras with less than 5 seconds left.

![image](https://github.com/user-attachments/assets/e4f3c611-8a47-42ae-bbeb-b0f4f7869fe0)

**Comment by michaelnpsp** [comment]
Grid2 relies on OmniCC addon to display the cooldown text, so you must configure the cooldown  appearance settings in OmniCC configuration.

In OmniCC you can make settings to be applied only to Grid2 or only to some some specific Grid2 indicator.
In the rules section of OmniCC you can use the pattern **Grid2** to target all Grid2 icons.

If you want to configure the appearence/behaviour of only one specific Grid2 indicator, you have to use a pattern like: 
**Grid2+indicatorname**, but removing all punctuation characters and spaces from the indicator name:

For example if the indicator name is:
**icon-center** 
you must use as rule in the OmniCC configuration:
 **Grid2iconcenter**

**Comment by michaelnpsp** [comment]
I added an option to hide the cooldown texture when omniCC is not disabled in version 2.8.50  (This is the only setting that cannot be configured in OmniCC).
