### ISSUE TITLE
Status - Buff tracking - Number of Stacks - Threshold Button missing

### ISSUE THREAD

**Issue by mohcow** [michaelnpsp/Grid2#265]
It seems like the threshold button for status buff tracking is gone. I disabled every addon and used a blank profile its still not there. you can set the colours but no threshold button.

see https://i.imgur.com/jebaEME.png

**Comment by michaelnpsp** [comment]
I don't know which threshold button are you talking about. There are threshold sliders, but those thresholds are only displayed when the coloring is based on remaining or elapsed time.
For coloring based on number of stacks, color1 is for stacks=1, color2 for stacks=2, etc, no sliders are used.

**Comment by mohcow** [comment]
Ah ok. I  was looking at the guide but didnt pay attent to it saying "remaining time". my bad.
