### ISSUE TITLE
Raid Debuffs Autodetection disabling itself automatically

### ISSUE THREAD

**Issue by fracture93** [michaelnpsp/Grid2#266]
Hello,

Using the latest version of Grid2, this happens with all other addons disabled.

To reproduce the issue: go to 'Status' -> 'Debuffs' -> 'Raid Debuffs' -> 'Miscellaneous' -> 'Debuff Autodetection', checkmark 'Enable Autodetection', once enabled, log out and log back in or reload UI and 'Enable Autodetection' will be disabled.

Am I doing something wrong, is this intended?

Thanks

**Comment by michaelnpsp** [comment]
This is the intended behaviour.  
Debuff autodetection is mean to be used only once on each dungeon/raid to collect the raid-debuffs, becaouse all debuffs collected are already saved/remembered and can be browsed in the raid debuffs configuration. So its not necessary to maintain the option always enabled.

Anyway enabling the raid-debuffs module for the current expansion in raid-debuffs setting, all raid debuffs must be already displayed without using the autodetection option.

If you simply want to display all debuffs, without further configuration, you dont even need to use the raid debuffs module, you can create a standard "debuffs group" in "statuses/debuffs/right panel" and configure the filter settings of the status to display all debuffs, or only the boss debuffs.

**Comment by fracture93** [comment]
The problem is that some debuffs are not included in the pre-configured debuff lists, causing it to not show up at all.  I like using the auto detect because it will sort it properly into the dungeon/raid boss so I can easily manage it and have it organized already.

I am confused why there is no mention of this behaviour on the settings toggle itself either.  I do not want to always display all debuffs, but I would like it to auto detect new debuffs and filter them into the proper dungeon/raid boss section.

**Comment by michaelnpsp** [comment]
Then you can enable the autodetection to collect the missing debuffs, but once the debuffs are collected, the autodetection option is not neccessary anymore.
Really the option was meant to be used only for me to collect the new debuffs and create the raid debuffs modules.
I am disabling the option on reload becase if i dont do that, players are going to keep the option enabled forever, and the module runs more slow with the option enabled.
