### ISSUE TITLE
Update Raid Debuffs

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#267]
In Priory of the Sacred Flame the starting trash hit with mortal strike would be good to add to debuffs list:

![image](https://github.com/user-attachments/assets/0f22b42f-8080-4ead-ac10-628912bbcdc7)

**Comment by michaelnpsp** [comment]
Y released  2.8.51-beta version, this version includes a new mythic+ dungeons module for raid-debuffs, that displays the mythic+ dungeons in one place, so now it is not necessary to enable modules for old expansions.
