### ISSUE TITLE
A list of raid-debuffs from trash dungeons S1 tww

### ISSUE THREAD

**Issue by Pellew** [michaelnpsp/Grid2#269]
Would it be possible to add all the debuffs from this list to the RaidDebuffs.
It is a list of the trash debuff from each dungeon for s1 in tww.
I tried my best to get them all, but maybe one or two is missing. 

/Pellew
[Trash debuffs dungeons spell id.txt](https://github.com/user-attachments/files/17005215/Trash.debuffs.dungeons.spell.id.txt)

**Comment by michaelnpsp** [comment]
Y released  2.8.51-beta version, this version includes a new mythic+ dungeons module for raid-debuffs, that displays the mythic+ dungeons in one place, so now it is not necessary to enable modules for old expansions.

**Comment by Pellew** [comment]
Thx alot for the great work :)
