### ISSUE TITLE
Treat poisons as dispellable for Shaman with Poison Cleansing Totem talented

### ISSUE THREAD

**Issue by Toludin** [michaelnpsp/Grid2#270]
Similar to showing Magic effects as dispellable for Priests when they talent into Mass Dispel, I think it would be helpful to treat Poisons as dispellable for Shaman who talent into Poison Cleansing Totem.

Added this to line 369 in GridUtils.lua:

`dispel.Poison = IsPlayerSpell(383013) -- Poison Cleansing Totem`

(I haven't actually confirmed this works just yet, I just looked up the cast spell ID for Poison Cleansing Totem in a log. I assume that's the spell ID to check on for `IsPlayerSpell()` here).

**Comment by michaelnpsp** [comment]
Try out 2.8.55-beta version
