### ISSUE TITLE
Icon Display Issue

### ISSUE THREAD

**Issue by danielsawan** [michaelnpsp/Grid2#274]
Hello,

I have a display issue that has been happening for some time now, but I never took the time to look into it. I usually display the role of a class below its corresponding square.

1) ![Screenshot 1](https://i.imgur.com/MGWyOE0.png)

The problem I have is that when I click on another square, the icon above the original square becomes hidden in the background.

2) ![Screenshot 2](https://i.imgur.com/IJGU8s0.png)

This behavior started occurring right after an addon update some time ago.

I would like to know if there is any configuration that could be applied to restore the behavior shown in 1).

Thanks for your help!

**Comment by michaelnpsp** [comment]
Check the icon indicator frame level, the frame level must be higher than the framelevel of the health bar indicator.

**Comment by danielsawan** [comment]
Hello @michaelnpsp,

Thanks for your suggestion. I have already verified the frame levels: the health bar indicator's frame level is set to 2, and the icon at the bottom (representing the role) is set to 9.

I believe the issue might be caused by the fact that the "role" icon at the bottom is somehow getting out of the frame to which it is bound.

Do you have any other ideas or suggestions that could help resolve this?

Thanks again for your assistance!

**Comment by michaelnpsp** [comment]
It seems now the game is rendering the icons in some weird way, if you move the  icon to the top or the lef  border the issue does not happen, only when the icon is at the bottom or right.
I think is not worth to implemente a work arround, its not usual to have the icons placed betweeen unit frames, and the workaround could break a lot of others things.

**Comment by danielsawan** [comment]
# Issue with Icon Rendering

Hello @michaelnpsp,

> "It seems now the game is rendering the icons in some weird way. If you move the icon to the top or the left border, the issue does not happen, but it does occur when the icon is at the bottom or right."

This is indeed very strange behavior. I appreciate your insights.

> "I think it is not worth implementing a workaround, as it is not usual to have the icons placed between unit frames."

I am only using the parameters provided by the addon but I completely understand your point of view.
