### ISSUE TITLE
[Request] Loading all class buff statuses

### ISSUE THREAD

**Issue by SilAntoine** [michaelnpsp/Grid2#275]
Hello,

Grid has class buffs preprogrammed by default.
However, I can't find a way to load them after copying my "blank" custom profile/layout.
I have to add class buffs one by one or use the default profile and customize the whole layout for each character.

Did I miss the option?

Thanks for the awesome add-on!
Antoine

**Comment by michaelnpsp** [comment]
The default grid2 profiles are very basic.  But depending of your needs you can use different approaches.
You don't need to use different profiles, you can use only one profile for several or all of your toons.

For example you can create all buffs in one profile, and inside the Load tab of each buff, setup filters to load each buff only for some specific classes or specs.

You can create a "Buffs" (plural) status, and add a list of buffs to display too.

Another posibility is to create a"Buffs: Blizzard" status (in statuses/right panel).  The Blizzard:Buffs status automatically displays the relevant buffs for each class. You must link this status to a icons (plural) indicator that displays all buffs in a row or column.

For more complex setups you can enable Themes (in general/general tabs), and create different themes for different toons, or roles or specs or content types (raid/group) etc.
With themes you can setup different appearances/sizes/positions/layouts for the unit frames, but without duplicating statuses and indicators (but indicators can be enabled/disabled per theme).

**Comment by SilAntoine** [comment]
Thanks a lot for the tips, I'll look into it!
