### ISSUE TITLE
[Request] Option to have another theme or profile if you have two or more layouts enable

### ISSUE THREAD

**Issue by Pellew** [michaelnpsp/Grid2#276]
Hi

Would it be possible to add the function to have a different theme or profile if you run with two or more layout at the same time. 

ex.
I have one profile or theme for my party/raid frame
I have another profile or theme for specific target to buff when i play evoker. 

![Skærmbillede 2024-11-11 085123](https://github.com/user-attachments/assets/b1b99dd5-0742-422f-a6ab-defc403a1e17)

I hope the request makes sense :)

**Comment by michaelnpsp** [comment]
I dont understand what you mean. Do you want a different size and/or position for your target or focus ? This can be done in appearance section.

**Comment by Pellew** [comment]
If i play aug evoker, i want to have the option to have to profiles or theme setup on diffent layouts showing at the same time.
One with my normal party frame 
Another set of frame for specific target in m+ or raids i have to keep track of their CD mostly offensives. 

The two grid2 frames you see is meant to be one for party frame, and one for tracking stuff as an evoker. 
It is not target or focus frame, but more like to set of party frame with different options to track.

Hope it makes better sense

![Skærmbillede 2024-11-11 085123](https://github.com/user-attachments/assets/d300d412-bc85-4ac2-855f-7d60682162f6)

**Comment by michaelnpsp** [comment]
Not possible with themes or profiles. But two separate groups of players/frames can be configured creating a custom layout with two detached headers, using the Layout Editor (General/Layouts/Editor).
But the issue is that no extra indicators can be created only for one group of players (I removed this option months ago because it was too convoluted and zero players were using the option).

**Comment by Pellew** [comment]
I have found the option to have two separate groups as you can see of the pictures, so thats good idd :)
okay - it was the option to have extra or specific indicators for only one of the group i was looking for.

**Comment by michaelnpsp** [comment]
In latest version i reactivate the UnitType condition for custom headers.
In the layout editor the Header Type name can be changed to a any user defined text, for example from "players"  to  "myTargets".
Then in any indicator configuration, you can go to the  "Load Tab" , and in  "Unit Type" condition select "myTargets" to activate/display  the indicator only for this kind of header.

**Comment by Pellew** [comment]
This works perfect - thx alot!
