### ISSUE TITLE
Inconsistent darkening of icons - Indicator "icon" and "icons"

### ISSUE THREAD

**Issue by mohcow** [michaelnpsp/Grid2#278]
I have a problem with the "icons" indicator being inconsistent in comparions to the "icon" indicator.

for context of this example: i am tracking missing Battle Shout. Top icon is a "icon" indicator and not darkend (like it should be) and the bottom is a "icons" indicator and darkend. this is a a new profile without any addons enabled.
 
https://i.imgur.com/MM0VaGL.png

config for both:

https://i.imgur.com/Yk52Hw5.png
https://i.imgur.com/5qWxy9z.png

Is this how it should be? If yes is there a way to make "reverse cooldown" work for missing buffs, so that missing buffs are not darkend? i know i can hide the animation in general but i want to track active buffs in the same group where a cooldown spiral is necessary

**Comment by michaelnpsp** [comment]
Try out version 2.8.63-beta

**Comment by mohcow** [comment]
Looking good, thank you! While we are on the topic of "icons" indicators. Are there any plan to have a progress text for these indicators? For "icon" indicators you could add a extra "text" indicator to make it work but for "icons" there is no such feature.

**Comment by michaelnpsp** [comment]
Grid2 relies on OmniCC addon to display count down texts in icon and icons indicators.
