### ISSUE TITLE
Feature Request: add "Not-disapellable by My" to Debuffs status options

### ISSUE THREAD

**Issue by mgalliou** [michaelnpsp/Grid2#3]
I currently use two "icons" indicators for my priest healer layout:
- the first one with just one "debuffs" status with the option "Dispellable by Me" checked.
- the second one with: one "debuffs" status with the option "Untyped Debuffs" checked, one "debuff: Curse" status and one "debuff: Poison".
Instead of having to use 3 different statuses for my second indicator to display the "Undispellable debuffs", I propose the option "Not dispellable by Me" to be added to the "debuffs" status options.
It would allow my layout to work with any class: with my druid for example, i had to duplicate my profile and change both "Curse" and "Poison" debuff statuses with "Disease" and "Magic".

**Comment by michaelnpsp** [comment]
Implemented in version 1.1.8-alpha
https://www.wowace.com/projects/grid2/files/3160829

**Comment by mgalliou** [comment]
Thank you for implementing this feature, it works pretty much as i expected except for one thing: the options hidden when "Dispellable by My" is the only one option selected are also hidden when the new options "Non Dispellable by My" is the only one selected. I think they should not be hidden in this case.
I'm talking about these options (expect for "Blacklist" that is staying visible):
![image](https://user-images.githubusercontent.com/3055136/104088519-e6124c00-5267-11eb-960e-92896cfbb231.png)
