### ISSUE TITLE
Feature request: Raid layout "By Group & Role w/Pets"

### ISSUE THREAD

**Issue by DocNessuno** [michaelnpsp/Grid2#31]
As per title. 
I personally find this (unavaiable) layout the most convenient for healing:

- Maintains group composition for raid assignments/positioning and to glance at group-based buffs
- Bunches tanks in the same group together (also bunches tanks in general to the same side) reducing movement needed to play whack-a-mole
- Allows to see/heal pets

At the moment we only have some similar layout that compromise on one of the above aspects:

- By Group & Class w/Pets
- By Group & Role
- By Group w/Pets
- By Role w/Pets

**Comment by michaelnpsp** [comment]
Added the  requested layout in Grid2 version 2.0.32.
