### ISSUE TITLE
"Show if missing" doesnt work for pets.

### ISSUE THREAD

**Issue by MartMlr** [michaelnpsp/Grid2#33]
I'm using this option to track if players or pets are missing certain buffs. (In my case Mark of the Wild and Gift of the Wild)
It works just fine for players but for some reason it doesnt work for pets. 

Method: Indicator: icon

Client Version: 2.5.2 (40488)
Addon Version: 2.0.24-bcc

**Comment by michaelnpsp** [comment]
Buffs are not displayed for pets in Grid2.
