### ISSUE TITLE
[Feature Request] Separate Themes for 5-man party (Dungeons VS Open World)

### ISSUE THREAD

**Issue by ojstilo** [michaelnpsp/Grid2#37]
**Context:** AFAIK the **Themes for 5-man Party** are currently available only for different specializations, not **different contexts**. This **enforces users to have one theme usable for both Dungeons and Open World**.

**Problem:** I prefer to have Party Frames closer to the middle when doing challenging content. However, I find this obtrusive when in a group while not in a dungeon.

**Proposed solution:** **Add some new Themes options for Dungeons and their different types (N&HC/Mythic & Mythic+)** - like there are themes for Raid (PvP/LFR/N&HC/Mythic). This way we could have a different setup for Party outside challenging content VS inside dungeons/M+.

**Comment by michaelnpsp** [comment]
Added Party Normal/Heroic/Mythic conditions in version Grid2 2.0.32
