### ISSUE TITLE
[Question / Feature request] Only track threat for tank-role units

### ISSUE THREAD

**Issue by drnoonien** [michaelnpsp/Grid2#38]
My use-case is that I want to track threat to know who's currently holding boss via Grid, but I don't want my Grid to light up like a christmas-tree during add-heavy phases like Sentinels on Sylvanas.

I realize this goes against the idea of tracking threat (see when a non-tank grabs and needs attention), but perhaps it could be justified as an option on the threat statuses.

**Comment by michaelnpsp** [comment]
declined
