### ISSUE TITLE
Incorrect debuff tracking as mage.

### ISSUE THREAD

**Issue by Guema** [michaelnpsp/Grid2#4]
I'm encontering a problem with "dispellable by me" debuff group.
I am creating a special display for raid/group members i can dispell with the current class im playing, without needing to create a profile for each character or class.

Here is the actual status i created : 
![image](https://user-images.githubusercontent.com/8943532/104095648-4de08b00-5298-11eb-9e9c-5db182612200.png)

problem : as a Mage, i see Magic debuffs through this status, even if i can't dispell them (as a mage i can only dispell Curses).
It seems to work correctly for my Resto Shaman, but, i am not sure if their is other problem like this. I didn't test other specs or class atm.

I will probably see if i can understand the code and see if i can do a pull request.

**Comment by michaelnpsp** [comment]
Try out latest Grid2 version. Dispellable filters code was recently refactored.
https://www.wowace.com/projects/grid2/files/3160988

**Comment by Guema** [comment]
Thanks a lot for your answer.
I just swapped to alpha channel and got 1.1.9 i will update as soon as i can be sure i cannot reproduce the problem on this new version.

Btw nice congrats for this nice addon.
