### ISSUE TITLE
Strongbox

### ISSUE THREAD

**Issue by sfjuocekr** [michaelnpsp/Grid2#42]
Strongbox recently deprecated the use of Curseforge, but supports git.

Sadly, it had some requirements and throws a hissyfit over how the releases are structured on the release page.

https://github.com/ogri-la/strongbox/

Maybe this is something you could fix on your end?

**Comment by layday** [comment]
Hi, the minimum requirement for strongbox is for the add-on zip to be attached to the GitHub release. Other add-on managers might also expect to find a `release.json` file as produced by the [BigWigs packager](https://github.com/BigWigsMods/packager).  There's a demo repo with manager-consumable releases at https://github.com/nebularg/PackagerTest.  I don't think there's proper documentation for any of this, unfortunately.
