### ISSUE TITLE
boss6-boss8 updates for Prototype Pantheon

### ISSUE THREAD

**Issue by gitarrg** [michaelnpsp/Grid2#44]
Hey there,

for Prototype Pantheon it would be good to track the units boss5. boss6, boss7, boss8 as those can be the seeds which need to be healed up throughout the fight.

I did a quick test setting up a custom header with these units.
- it does populate them correctly
- with "use Blizzard Frames" disabled I'm able to interact with those! (yeah!)
- only boss5 does receive updates (hp and/or buffs)

Here is a quick screengrab:
(at around 2:28 into the fight, I'm trying to test)
https://www.youtube.com/watch?v=8c0FOHAeJ2c

**Comment by michaelnpsp** [comment]
I just reviewed the latest blizzard code for patch 9.2, and it seems the game only tracks and create boss1 to boss5 units, in my game client this code:
/script print(MAX_BOSS_FRAMES)
only prints 5, that is the maximum boss frames tracked by the game.
Which extra addon are you using to display boss6 to boss8 ?, because  these units should not exist.

**Comment by gitarrg** [comment]
Hey,

I've setup an addition custom header and simply used boss6,7,8 there:
![image](https://user-images.githubusercontent.com/82116652/158455443-c5b39986-3013-493e-896a-20bdecd53301.png)

I've heard Vudhoo does support it somehow as well.
And someone mentioned those unit would be tract via `arena1`, `arena2` etc

**Comment by michaelnpsp** [comment]
In a Grid2 custom header you can type any text, grid2 does not check if the unit is valid or not at that point, but this does not mean the game is going to create the typed units,

**Comment by gitarrg** [comment]
Hey there,

I did a quick test using Vudho (to see if they indeed work), as well as testing another Addon suggested to me (https://www.curseforge.com/wow/addons/kextrabossframes)

They both seem to work correctly:
https://youtu.be/7zdLMT0iBMY

**Comment by gitarrg** [comment]
Hey again,

it seems ElvUI also added support for those boss-units:
![image](https://user-images.githubusercontent.com/82116652/159703440-6f2fcd77-dd80-47de-bac6-31f1d74ca86f.png)

I've had a quick look at the commits... this one seems to implement most of the update logic, which is all custom
https://github.com/tukui-org/ElvUI/commit/e655d0b3d0c7f55a860e39eb9960840a75aa676b

**Comment by michaelnpsp** [comment]
I added a timer to update the bugged bosses frames in version 2.0.37-beta. Not tested, i have no access to the Prototype Pantheon  boss.

**Comment by Squishes** [comment]
I tested it tonight in LFR. The HP and indicators weren't updating, though mouseover heals were casting on the frames

**Comment by michaelnpsp** [comment]
Which update frequency are you using for the health updates, normal or instant ?
The option is on statuses/health&heals/health-current.

**Comment by Squishes** [comment]
Instant

**Comment by michaelnpsp** [comment]
Instant update frequency does not work with new bosses units, because combat log events are not fired too or these units. Blizzard have to fix this mess and add the missing code and events  to the game, Tired of adding  trillion of tricks to the addon because blizzard does not fix his own bugs :(
I can try to fix this thing in another way  but then only  health are going to be updated (another indicators will not work in the new bosses frames).

**Comment by Squishes** [comment]
is it possible to force the non-instant update frequency setting for just those units? This does sound incredibly frustrating to deal with; I appreciate your effort to work it out for us!

**Comment by michaelnpsp** [comment]
Try out 2.0.38-beta, i moved the fix to health status, so this version must update the health even with instant updates. Keep in mind that auras and some other statuses are not going to work on the bugged bosses units,
I added a"Units per Column" and "Hide Empty" options to Layouts/General for bosses units, with this new options there is not necessary to create custom headers to display bosses, enabling the "Display Bosses Units" in this section should be enough.

**Comment by Squishes** [comment]
awesome I'll check it out. Having working health bars would be plenty, though statuses would be nice, it's not that hard to deal without them for this use case

**Comment by Squishes** [comment]
The health updates now!
