### ISSUE TITLE
Feature Request - Blacklisting debuffs from boss frame

### ISSUE THREAD

**Issue by J0nners** [michaelnpsp/Grid2#45]
![image](https://user-images.githubusercontent.com/102998027/161627230-addbb771-62ab-4a70-a0b9-f880052f4233.png)
Specifically this tier for Anduin and Pantheon - this feature would be incredibly useful as the main important thing for healers to track is the adds and the frame can get cluttered if the boss has several debuffs as well.

**Comment by michaelnpsp** [comment]
You can use the Unit Reaction filter (Load tab inside each debuff status) to activate different debuffs depending of the type of unit (friendly or hostile).
