### ISSUE TITLE
request! individuall addjustment for detach header

### ISSUE THREAD

**Issue by tasimi** [michaelnpsp/Grid2#46]
im sorry i don't know to mark this as an request an not an issue.

i would love to addjust groups like "pets" and "bossframes" in size and for the "bossframes" allso for the indikatiors/status
so i can make those bars smaller then my normal bars cause i don't have do see all the things on them i see on my normal bars.

if you don't understand what im talking about, pls let me know. i will try then another text. english is not my mothertounge and it is a bit complicatet to describe what i want.

**Comment by shambles1213** [comment]
Hello, also very interested in this question, 
with the release of wotlk pets in raids is becoming too much and this feature would be very

**Comment by shambles1213** [comment]
Hello, also very interested in this question,
with the release of wotlk pets in raids is becoming too much and this feature would be very useful

**Comment by michaelnpsp** [comment]
In Version 2.0.57-beta frame sizes, units per column and anchor points can be individually configured.

**Comment by tasimi** [comment]
i lookinf forward to test this! thx very much for puting work into this!!!!!!
