### ISSUE TITLE
No license file or license mentioned

### ISSUE THREAD

**Issue by fxrs** [michaelnpsp/Grid2#50]
On an other site the "zlib/libpng Lic..." is mentioned. Here I see no reference.

**Comment by michaelnpsp** [comment]
Github don't have the zlib/libnpg license in its selection list, but you have the license terms in the README.txt file inside the project, maybe i could rename the file to LICENSE.txt for better visibility.

**Comment by fxrs** [comment]
Oh, I missed that. Now I noticed, searching for "license" on the page finds the text in the README.txt. So on one side it is easy to find, on the other I missed it when I only looked at the other locations. 
I thought github referenced it if you have a file named LICENSE.txt even if it would be "other" but I haven't checked.

**Comment by michaelnpsp** [comment]
I renamed the file to LICENSE.txt for better visibility.

**Comment by michaelnpsp** [comment]
I renamed the file to LICENSE.txt for better visibility.

**Comment by michaelnpsp** [comment]
Renamed the file to LICENSE.txt for better visibility.
