### ISSUE TITLE
Just a question for hiding grid2 in condition

### ISSUE THREAD

**Issue by hobulian** [michaelnpsp/Grid2#51]
How can i hide grid2 only when in raid lesser then 6 man? Cannot find it how..

**Comment by hobulian** [comment]
Which means not in instance but in state of raid with lesser then 6 man

**Comment by michaelnpsp** [comment]
You can't, you can hide grid2 when in party or solo for example, but there is no option for <=5 players while in raid.
This is a very specific filter, it could be implemented with a weakaura maybe.

**Comment by hobulian** [comment]
https://wago.io/KKmRi8VeI

Like this one?

**Comment by michaelnpsp** [comment]
Sorry provided link gives my a 404 not found error.

**Comment by hobulian** [comment]
Sorry Link was

https://wago.io/F7SZrocdy

like this one.

**Comment by michaelnpsp** [comment]
Yes the aura linked should work (but it does not hide the grid2 window when not in raid),.
The only issue:  It is inefficient because the code is using a loop to calculate the raid members instead of simply use the game  GetNumGroupMembers() function to get the number of raid members.

**Comment by hobulian** [comment]
Thank you for your helps!
