### ISSUE TITLE
Tracking the same debuff as two different statuses with only one checked as "Track by SpellId" breaks the other one

### ISSUE THREAD

**Issue by drnoonien** [michaelnpsp/Grid2#52]
I accidentally discovered this behavior while testing something unrelated. Not sure what the actual use-case is for this, but I figured you'd be interested in knowing about it in case it has other side effects.

**Client**: Retail
**Grid2 version**: 2.0.43

Steps to reproduce:
- Add a debuff status (A) for Weakened Soul (6788), use the spell id as the input, leave "Track by SpellId" unchecked
- Add a second debuff status (B) for Weakened Soul (6788), use the spell id as the input, check the "Track by SpellId"
- Apply Weakened Soul to yourself

Expected:
- Both status A and B should trigger

Actual:
- Only status A triggers, B (the one tracking spell-id) is ignored

**Comment by michaelnpsp** [comment]
Already known behaviour, It was coded in this way for performance reasons.

**Comment by drnoonien** [comment]
Goodie, closing this issue in that case.
