### ISSUE TITLE
Custom layout hide tanks issue

### ISSUE THREAD

**Issue by rferesteanu** [michaelnpsp/Grid2#55]
Hello, what I'm trying to achieve is a setup where I have one frame of only assigned tanks and one other frame for everyone else except the tanks. I thought this custom layout below would do just that but it does not seem to be working. Am I doing something wrong or is this a bug? Addon version is 2.0.34-classic for Classic SoM 1.14.2

![image](https://user-images.githubusercontent.com/16353894/171958848-692760db-0cf6-470a-bc45-5a930c5f7558.png)

**Comment by michaelnpsp** [comment]
Unfortunatelly the problem relies on blizzard code (in som and tbc versions) so i cannot full fix the issue. 
In version 2.0.44 I fixed the issue in the grid2 customheaders code, but this means you have to Disable Blizzard Frames.
So to enable the fix you have to go to General/Layouts/General and Uncheck the "Use Blizzard Unit Frames" Option.
But keep in mind that if you disable blizzard unit frames, the unit frames changes cannot be updated while in combat, so if some player joins or leaves the raid while in combat, grid2 cannot remove or add the players.

**Comment by rferesteanu** [comment]
It works now! Thank you very much for the quick fix

**Comment by jeromeBor** [comment]
Sorry for the late answer, but as today 21/10/2024, I can't see the option "General/Layouts/General and Uncheck the "Use Blizzard Unit Frames"" and I also have the bug where tanks role show up in dps group. I play WOW SOD.
I have somewhere "show blizzard raid/group/ etc" frame, but it's not fixing my issue.

I created a custom layout in editor with everyone but tank, and second one with tank only. 
Tank only group works fine, but other one still show tanks. 
I can't find where is my custom group data is located

Any suggestions ?

**Comment by michaelnpsp** [comment]
I removed the "Use Blizzard Unit Frames" option for general use time ago, because people was disabling the option for no important reason and then blaming that people joining the raid while in combat was not visible (this is a side effect of disabling this option because non-blizzard code cannot  change unit frames in combat).
Now, to make the option visible in configuration  you must type into chat something like :

`/script` Grid2.isDevelop=true

**Comment by michaelnpsp** [comment]
Update to version 2.8.58-beta, the "Blizzard frames" options should be visible now for  classic/vanilla clients in:
"General/Layouts/General" Tab.

**Comment by jeromeBor** [comment]
> Update to version 2.8.58-beta, the "Blizzard frames" options should be visible now for classic/vanilla clients in: "General/Layouts/General" Tab.

Perfect, it's working thank you ! 
And I really don't understand why are people blaming about not being to see if **someone left or join raid while in combat**. I mean, it's really not an inconvenience, is it ?
Thanks a lot !
