### ISSUE TITLE
Feature Request: Line of sight frame change color

### ISSUE THREAD

**Issue by Avishai97** [michaelnpsp/Grid2#59]
Basically title, just like you can change color of frame if they have poison, mind control etc I would love if I can change color of the frame if a friendly player is not in line of sight.

**Comment by michaelnpsp** [comment]
Not possible.

**Comment by Taquito51** [comment]
Reopening this request as I can see Blizzard's default raid frames can use frame alpha to show targets not in line of sight (Mug'Zee gaol).

Is still not possible to implement?

**Comment by michaelnpsp** [comment]
Goto:
https://github.com/michaelnpsp/Grid2/issues/283
