### ISSUE TITLE
Cooldown swipe on icons is offset 1 pixel to the right

### ISSUE THREAD

**Issue by Malenkie** [michaelnpsp/Grid2#6]
This makes the cooldown swipe go 1 pixel beyond the border, or if not using a border, there is a 1 pixel line on the left of the icon indicator which is not covered by the swipe.

**Comment by Malenkie** [comment]
Excuse the double posted closed version of this issue submit, I got a 404 but it apparently submitted anyway.

**Comment by michaelnpsp** [comment]
The cooldown swipe is correctly aligned to his parent. Use a different scale or move slightly the unit frames. The game  sometimes does not correctly align or display some lines depending on the screen scale and frames position.
