### ISSUE TITLE
Layout Preview

### ISSUE THREAD

**Issue by ghost** [michaelnpsp/Grid2#60]
Is there a way to preview a layout? I'd like to be able to set everything up to my liking without going into Alterac Valley not contributing. I could not find anything related in the options.

**Comment by michaelnpsp** [comment]
Goto General / Layouts / By Group Type and Click on the magnifying glasses icons displayed on the right of the selected layouts.
If you are using themes goto:
Themes / Select a Theme / Layouts / By Group Type
