### ISSUE TITLE
RaidDebuffs: Debuff Type Color 

### ISSUE THREAD

**Issue by gitarrg** [michaelnpsp/Grid2#61]
Hey there,

Would it be possible to add a "Use Debuff Type Color"-Feature (similar to the one we have for the generic "Debuff"-Status) to the RaidDebuff-Status.
I prefer setting up any raid/dungeon debuffs via the RaidDebuffs-Status, as provides a very nice overview of the debuffs configured for each Boss/Dungeon. However its a bit of a downside to be unable to tell if something is a magic, posion or curse-debuff.

**Comment by michaelnpsp** [comment]
Implemented in Grid2 version 2.0.50
