### ISSUE TITLE
Feature Request: Add option to load status if the unis is belong to specific spec

### ISSUE THREAD

**Issue by 71864315** [michaelnpsp/Grid2#62]
Currently there is option to load status if the unit is belong to specific **class**, but it would be great if we could filter statuses also by unit **spec**.

**Comment by holypalaswe** [comment]
In wotlk you will have the [UnitGroupRolesAssigned](https://wowwiki-archive.fandom.com/wiki/API_UnitGroupRolesAssigned) api, would be cool to have that as a load condition for unit role as an alternative to spec, if it's easier to implement.

**Comment by michaelnpsp** [comment]
Grid2 Retail version already have an option in load tab for class&spec. In Classic versions (vanilla, bcc, wrath)  character specs don't exist so the option is disabled.

**Comment by michaelnpsp** [comment]
Unit filters are only processed when the unit joins the raid so i cannot add a filter that can change in the middle of a raid.
