### ISSUE TITLE
WotLK support

### ISSUE THREAD

**Issue by padkipz** [michaelnpsp/Grid2#63]
Morning,

Not sure if you have beta access, but currently getting an error on WotLK beta. With all other addons disabled, this error pops up:

``1x ...faceGrid2\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PLAYER_SPECIALIZATION_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Grid2\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@Grid2\GridCore.lua"]:159: in function <Grid2\GridCore.lua:148>
[string "=[C]"]: ?
[string "@Grid2\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...faceGrid2\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Grid2\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Grid2\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...faceGrid2\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>``

The addon itself mostly works, you're able to see players in a group, and click on frames, but no names display, and it errors fairly frequently with the above.

Happy to help run some tests if you don't have access to beta.

**Comment by ap0yuv** [comment]
thats usually an indicator that addon is thinking you are playing retail.

changing  the value "30000" line 19 and 21 in GridCore.lua to "40000" let it load properly for now. havent been able to test out anything behind logging in yet.

**Comment by padkipz** [comment]
That worked perfectly - no other errors after that.

Checked through all the settings, and tested different profiles.

Thanks a bunch, and let me know if you want me to do any other testing.

**Comment by michaelnpsp** [comment]
Grid2 version "2.0.46-beta-bcc" should fix the issue.
