### ISSUE TITLE
Feature Request: Raid debuffs blacklist

### ISSUE THREAD

**Issue by Kowalskii137** [michaelnpsp/Grid2#64]
Currently in raid when I use autodetection, I see too many debuffs, but without this option I can't see some debuffs. I can add custom debuffs. But then I can just add all debuffs...

**Comment by michaelnpsp** [comment]
Autodetection is not mean to be used in this way, It is used once per dungeon or raid to collect the debuffs for the raid debuffs module. After the debuffs are collected and added to the raid debuffs database the autodetection option is not necessary anymore, simply you can go to the raid debuffs configuration and  disable the undesired debuffs.
If you want to see all the debuffs except a black list,  you can create a Debuffs status:
1. Goto Statuses/Debuffs, 
2.  On the Right panel select "Debuffs" in the select type option.
3.  Choose a name to the new status, if you dont like the generic "Debuffs" name.
4. Push Create
5. Then Click on the new created Debuffs status, and you have a lot of options to display different kind of debuffs and to create a blacklist or a whitelist.
6. You must link the new create status with some indicator, like the icon center indicator or whatever.
