### ISSUE TITLE
Grid2 Error Importing profile

### ISSUE THREAD

**Issue by Yameuu** [michaelnpsp/Grid2#66]
Hey

I've been getting this error once i try to import a profile into grid2.
It worked fine before but after i transfered servers i get this error.

"Grid2 Import profile failed: ...Bars_EZ\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:179: Supplied data misses AceSerializer terminator ('^^')"

 

Would appreciate any help <3

**Comment by michaelnpsp** [comment]
Corrupted profile, maybe try to recover an older profile.

**Comment by Yameuu** [comment]
ah shit oh well i have an old one where the one i did was based from, but i did a ton of work on it

well thx for ur time
