### ISSUE TITLE
[Question] heals-incoming: ignore spells

### ISSUE THREAD

**Issue by phuze** [michaelnpsp/Grid2#67]
Is there any means by which I can ignore particular spell(s) related to heals-incoming?
Specifically, I'm looking for a way to ignore heal over time spells.

Is heals-incoming tracked/provided by Grid2, or is that piece driven by LibHealComm?

**Comment by michaelnpsp** [comment]
In retail Grid2 uses the game heals API so no configuration is possible.
In classic Grid2 can be configured to use heals API or LibHealComm, but LibHealcomm is a dead project, it is not maintained so  i am going to remove this option in the future.
When Libhealcom is used, in Statuses/Heals/Heals incoming there is some configuration options to filter the type of heals and to setup a time band.

**Comment by phuze** [comment]
Appreciate the response and insight mate 👍
