### ISSUE TITLE
Layout editor bug in Grid2-2.0.49 on classic 3.4.0

### ISSUE THREAD

**Issue by literofcola** [michaelnpsp/Grid2#68]
Wrath classic has reintroduced the three roles, "Tank Healer Damage", which seems to be conflicting with the "Main Tank", "Main Assist" roles used in the layout editor for classic/tbc

In GridLayoutsEditor it seems safe to eliminate the RETAIL flag:

local RETAIL = true --not Grid2.isClassic

Now all roles are selectable and the layout works as expected

**Comment by michaelnpsp** [comment]
Fixed in version 2.0.50
