### ISSUE TITLE
Detach tank frames + keybind frames

### ISSUE THREAD

**Issue by raden38** [michaelnpsp/Grid2#69]
Hi team !

It is possible to add a feature to detach tank roles frames or just duplicate them ? By doing this, it can be possible to have bigger frames for tanks and tracked buff / debuff on them individualy instead of the same config as raid.

In addition it will be realy nice if you can add a keybind option to target these frames or even just "Tank role 1", "Tank role 2" etc... if possible.

Realy hope you will add this like it is possible with Vuhdo addon. Cause Grid is just way graphicaly better and I hope to be able to reuse :)

Thanks a lot for this great job team !

Best regards,

Glock

**Comment by michaelnpsp** [comment]
You have to create a custom layout using the Layout Editor: General/Layouts/Editor.
Using the layout editor you can create a new custom layout with a header (group of units) to display all units except tanks and a second header to display only tanks. 
There is an option the the layout editor to detach headers or you can use the  "detach all groups" option in /General/Layouts/General Tab.

**Comment by raden38** [comment]
Ok thanks a lot for this answer i will try this !
