### ISSUE TITLE
Statuses only passing on one debuff

### ISSUE THREAD

**Issue by sfjuocekr** [michaelnpsp/Grid2#75]
I use an "icons" indicator on the "top" part of the frame, I have a "typeless" debuff status set to display there.

Now when we are doing Goondrak and we get Eck, it is shown on all members with Eck as intended. But when I chain into HoL and party members get the overcharge (or discharge thing with the blue beams) only Eck is shown if Eck is applied.

If Eck was not applied, it would show me the discharge.

I'd like a catch all like "typeless" to show me more than one debuff when possible?

**Comment by michaelnpsp** [comment]
Typeless debuff is a single debuff status, so only tracks one debuff. You have to create a debuffs (plural) status and configure the debuffs filter to not display typed debuffs.
1. Click on Debuffs.
2. On the right panel in "Select Type" option select "Debuffs"
3. Type a descriptive name for the new status (the default "debuffs" name is too generic).
4. Click Create.
5. Goto the new created status and uncheck the "Typed debuffs" option.
6. Link the status to the icons indicator.

**Comment by sfjuocekr** [comment]
Ah got it, probably should have fiddled with it a bit more!

**Comment by sfjuocekr** [comment]
Actually, the I remember why I did not use the "debuffs" status!

It doesn't let me disable "non dispellable" for example, I just want the typeless debuffs to show. Right now it also shows me diseases, which I can actually dispel.

**Comment by sfjuocekr** [comment]
It wouldn't be possible to have the "single" statuses show more icons?

For example if I were to use the debuffs status, I would like magic/curse on the right and disease/poison on the left. But this is currently not possible with the "multiple" status.

I've had it more than often happen to me that I missed a sheep, simply because I was ignoring a slow on a stationary caster. So I added an extra icon for sheeps and whatnot, but if the "single" statuses would be able to show multiple debuffs... that problem would never occur.

I like the idea of the debuffs type, but it is very limited in what it can do for me.
