### ISSUE TITLE
Improve release distributions

### ISSUE THREAD

**Issue by Porkepix** [michaelnpsp/Grid2#77]
Using https://github.com/ajour/ajour as a tool to manage addons, I encountered a couple of issues around it. First and foremost, Grid2 produce release packages on this GitHub to be used with such addon manager, which is a good thing (many addons doesn't do so).

However, it also happens that there seems to have wotlk classic and retail releases in the same GitHub releases, and even releases with assets only for classic (eg. versions 2.0.51 to 2.0.54). This is confusing such addon manager which seems to pick wotlk archives to use for retail. The addons manager also pick beta releases whatever the channel is (dunno if the release channel is applicable to GitHub though). This might be caused by beta releases being tagged on GitHub as "latest release" while this could be pre-releases instead.

Would you happen to have ideas to make it more usable in there without encountering the aforementioned issues? And at the very least have assets for both classic and retail for one given version, even if it doesn't contain any changes related to one of them?

**Comment by michaelnpsp** [comment]
I dont want to force players to upload a lot of irrelevant updates, but I can avoid to mark beta versions with  the "latest release" tag,

**Comment by Porkepix** [comment]
> I dont want to force players to upload a lot of irrelevant updates, but I can avoid to mark beta versions with the "latest release" tag,

Do you mean to upload release with a change in number but nothing in it, like a release with changes for classic but none for retail?

Then do you see maybe another solution to have Grid2 usable with such add-ons managers? There are already correctly built tarballs (which by far isn't the case of every addons), but the problem here is that the manager grabs whatever it finds, here the wotlk release (and correctly detect it as 3.4.0 game version), besides installing betas, leading to obvious issues.

So maybe it wasn't planned to have retail/classic/wotlk releases from the same GitHub tag while this is a pretty standard way of doing things?

I'm not an addon developper, but intuitively I'd have think it would be quite hard to have a common codebase and that it would have required different repos and therefore different releases numbering.

**Comment by michaelnpsp** [comment]
I have no good solution, other addon managers are working fine displaying all available versions.  Maybe a good starting point will be to not ignore the release.json file information,  picking the wotlk version if there is no retail version available clearly is a bug.

**Comment by Porkepix** [comment]
> I have no good solution, other add-on managers are working fine displaying all available versions. Maybe a good starting point will be to not ignore the release.json file information, picking the wotlk version if there is no retail version available clearly is a bug.

Well it actually picks the wotlk version whether others are in the same release or not. I guess there's not much more to do from here than not having beta releases tagged as latest then.
Unfortunately the add-on manager developer seems to have abandoned the project for the time being, so I guess there's nothing more to get here, and it doesn't seems to remains a lot of good add-on managers working from eg. GitHub repo urls like the one I used to deal with CF closing most of interactions with it.
