### ISSUE TITLE
Adjusting coords of icon texture to completely hide default blizzard border

### ISSUE THREAD

**Issue by lamboley** [michaelnpsp/Grid2#79]
Hi,

It is not an issue but a request.
At the moment you are using the following for the coordinate of the texture for both indicators **Icon** and **Icons**.:

`frame.icon:SetTexCoord(0.05, 0.95, 0.05, 0.95)`

This make so you can still see the default border of blizzard in the corner of the icons. Some of us don't want to see these border.
Would it be possible to have an option in the layout of the indicator that let use handle this? 

The option would work the same way as the **Zoom** option in Weakauras Icon.

At the moment I have to edit your code and use the following to not see the border:

`frame.icon:SetTexCoord(0.08, 0.92, 0.08, 0.92)`

What do you think ?

**Comment by michaelnpsp** [comment]
The suggested change does not fix the issue because the texture coordinates are provided by the statuses,. This needs a fix in another place, maybe a general option or only an option for buffs and debuffs.
Meanwhile you can change the coords in the function  status:GetTexCoord()  inside GridStatus.lua file.
function status:GetTexCoord()
	return 0.05, 0.95, 0.05, 0.95
end

**Comment by lamboley** [comment]
I am using the indicator **icons** with a status Debuffs and status Buffs and your code dosen't work while mine does. Did you test?

**Comment by michaelnpsp** [comment]
Icons (plural) indicator have some speed optimizations based on that in current grid2 implementation only buffs and debuffs statuses implement multiple icons.

**Comment by lamboley** [comment]
I see, thanks you for the explanation.

**Comment by michaelnpsp** [comment]
Added this feature in version 2.0.57-beta
