### ISSUE TITLE
REQUEST!! include / exclude pet & boss frames from indicators

### ISSUE THREAD

**Issue by tasimi** [michaelnpsp/Grid2#83]
it's me again! thx again for making my last wish come true ;) (and it works just fine!)

but: is it posible that for pet and boss groups can be exclude form the indcators? i mean i have many indicaotrs like buffs on the frames in general but i don't really need to see if a pet has absorb or how long my mastery hot is on it. so it would be awsome if i could determ on wich frames som of the indicators are shown and on wich not.

thx again for your time to maintain grid2!

**Comment by michaelnpsp** [comment]
You can filter buffs and debuffs using the Load tab of each buff/debuff, for example to display some buffs only on Friendly units (Unit reaction filter), but currently there is no filter for pets.

**Comment by tasimi** [comment]
so.. if i set the load option to "only show if unit role is tank, heal, dd" then it won't load on pets?

**Comment by michaelnpsp** [comment]
Yes, pets have the None role.

**Comment by tasimi** [comment]
then everything is just fine. have to deal with some buffs/debuffs and the load options! did not know that this was possible! thx again!

**Comment by michaelnpsp** [comment]
I added a new "Unit is Pet" filter to the Load tab in Grid2 2.0.62-beta version.
