### ISSUE TITLE
Hiding native raid frames causes UI issues

### ISSUE THREAD

**Issue by VeridicalCode** [michaelnpsp/Grid2#84]
Checking the [hide Blizzard raid frames] option in the general tab causes the quest log frame to become huge and change location. Tested with clean SavedVariables and no other addons active; happens whether actually in a raid or ungrouped.

**Comment by michaelnpsp** [comment]
Which Grid2 version ?

**Comment by GitPSj** [comment]
Changing the "hide blizzard raid frames" does not deactivate the (5man) party frame.

**Comment by michaelnpsp** [comment]
The party frames issue should be fixed in version 2.0.62-beta
