### ISSUE TITLE
Debuffs Autodetection does not persist after login

### ISSUE THREAD

**Issue by Sythr4l** [michaelnpsp/Grid2#85]
Enabling Raid Debuffs autodetection does not persist after logging out.; I have to re-enable it after re-logging into a character.

**Comment by michaelnpsp** [comment]
Working as intended. Debuff autodetection is not mean to be always enabled,  it should be used once per boss to collect debuffs of each boss, then it is not necessary.
If you want to simply see all boss debuffs without more setup, do not use raid debuffs, you can create a "Debuffs" (plural) status, and configure the Debuffs filter to display Boss debuffs.

**Comment by Sythr4l** [comment]
thanks for the quick response!  I had been using it to enable mythic plus debuffs.  I'll look to add them manually.

**Comment by michaelnpsp** [comment]
When the autodetection is enabled grid2 remember and store all autodetected debuffs in a database, so its not necessary to autodetect the debuffs more than once, the debuffs are going to be displayed even with the autodetection option disabled:
You can go to:
Statuses/Debuffs/Raid Debuffs  
Select "Shadolands" or "Custom Debuffs" in the In "Select Module" option.
Select a dungeon In the "Select Instance" option.
And the addon will display a list of all autodetected debuffs for that dungeon. There you can configure the debuffs: enable/disable debuffs, change priorities, etc.
