### ISSUE TITLE
Feature Request: Load Status if NodeID/ SpellID is known

### ISSUE THREAD

**Issue by mohcow** [michaelnpsp/Grid2#86]
Since Dragonflight added a plethora of talent options it would be nice to be able to load statuses just if certain spellID/nodeID are you known.

Most obvious example would be dispel types that might or might not be specced.

**Comment by michaelnpsp** [comment]
Some other examples ? Because for dispell types already exists a status working in this way: you can create a "Debuffs" status and enable the "Dispellable be me" filter in the status configuration.

**Comment by mohcow** [comment]
No other examples. But the "dispellable by me" filter doesn't seem to take into consideration if f.e. Holy Priests "improved Purify" is specced or not. Shows the disease debuff regardless. But you are right, if this works properly then there is not need for that feature.

**Comment by mohcow** [comment]
#87

**Comment by michaelnpsp** [comment]
Thanks for the patch.
