### ISSUE TITLE
[Question] Debuffs for Dragonflight M+ Season 1

### ISSUE THREAD

**Issue by kayti-wow** [michaelnpsp/Grid2#89]
How are you planning to handle the raid debuffs module for DF M+ Season 1?

- Temple of the Jade Serpent: there is no Mists module, and the encounters have been changed quite a bit since original MoP anyway
- Shadowmoon Burial Ground: covered by the WoD module, but missing a couple of debuffs that might be new
- Court of Stars and Halls of Valor: both missing trash debuffs, some boss spells are missing, and some spellids have changed
- DF dungeons: all missing trash debuffs

I can supply a gist of the debuffs I have autodetected on Beta if you need it.

**Comment by michaelnpsp** [comment]
I cannot collect these debufffs myself, i can reenable the MoPs module and add missing debuffs provided by players.

**Comment by kayti-wow** [comment]
@michaelnpsp You can find my exported debuffs here: https://gist.github.com/kayti-wow/8d1a7006cf2bd67b7688491e98f6d9f1

Note that even the old dungeons have changes - either new abilities or changed spell ids - so you may need to come up with a plan for handling debuffs in the old Challenge modes vs the new M+ versions.  Perhaps having a new module per season would be a good idea?

**Comment by michaelnpsp** [comment]
I think that its not necessary to create different versions, when the debuffs dont exist simply they are not displayed.

**Comment by kayti-wow** [comment]
> One question, why are there a lot of repeated debuffs in the exported debuffs ? Only one debuff is necessary, raid debuffs module discards all debufs with the same name except one when the debuffs are loaded because by default debuffs are tracked by name.

The autodetection definitely created a few duplicates as Blizzard in their wisdom have given the same name to multiple spells on some encounters (e.g. the two Chillstorms in Ruby Life Pools).  However, I did add some additional debuffs by taking the spellids from my logs and then using the Add Raid Debuff feature to allocate them to the correct encounter.

**Comment by michaelnpsp** [comment]
i added Mists of pandaria module and your debuffs in version 2.0.67.

**Comment by kayti-wow** [comment]
Perfect, thanks.

Have you given any further consideration to creating an M+ module containing both seasonal and standard affixes?

For S1 thats:

- Mark of Wind ( 396364 )
- Mark of Lightning ( 396369 )
- Lightning Strike [Player got hit by the blue swirly and is stunned] ( 394873 )
- Primal Overload [Players didn't get rid of the debuff correctly and became stunned] ( 396411 )

Plus the standard ones:

- Burst ( 243237 )
- Grievous Wound ( 240559 )
