### ISSUE TITLE
Tracking availability of defensive cooldowns

### ISSUE THREAD

**Issue by jnwhiteh** [michaelnpsp/Grid2#9]
Hey there! I've been working to create my healer UI with Grid2 and it's been rock solid, so thank you! I am looking to be able to track the availability of defensive cooldowns for tanks, particularly for use in m+ and in raids. Obviously the APIs don't provide any tracking, but I'm hoping to be able to add this to Grid2.

Is that something you'd consider integrating into Grid2 core, or would you prefer something like that be built as a separate addon? Do you see any reason why it wouldn't be possible to integrate as a status type that could fit into an "icons" indicator?

Thanks for any design help/discussion you're able to provide!

**Comment by michaelnpsp** [comment]
Is there any reason to not create and use "Statuses/Buffs/Goto Right Panel/Select Buffs:Defensive Cooldowns/
buffs group status ?

**Comment by jnwhiteh** [comment]
That would show when those cooldowns are active on player, not when they are available to be used (which is what I'm looking to capture). Sorry for the confusion!

At the moment it seems like something like OmniCD with some padding is a more realistic way to go about doing this. Thanks for the help!
