### ISSUE TITLE
Feature - Raid buff tooltips

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#92]
Any plan to give people the option to add tooltip to debuffs?

**Comment by michaelnpsp** [comment]
1. Goto "Indicators/tooltip"
2. Enable "Advanced tooltips" option 
3. Assign the desired debuffs or raid-debuffs in the tooltip "Statuses" Tab.

**Comment by martheli** [comment]
I have added tooltips to raid debuffs:
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/d9c77e49-5f1c-4984-bf8e-0d7c40016826)

But when I hover over one of my debuffs, I don't get spell tooltip.
