### ISSUE TITLE
Adding a blacklist to a debuff group fails

### ISSUE THREAD

**Issue by lwalter** [michaelnpsp/Grid2#97]
Grid2 version 2.1.0
Repro steps
1. Create a new status -> Debuffs
2. Enable Blacklist
3. Enter "Light of the Martyr" into the Blacklist pane and click Accept

Expected outcome: the blacklist is saved
Actual outcome: grid2 closes and the following message is seen in chat: "Grid2 Import profile failed: Invalid Hex string"

**Comment by michaelnpsp** [comment]
Working fine here, the error displayed has no sense because this can only happen using the profile import button. 
Try runing Grid2 standalone (no other addons enabled) and enable lua errors, maybe the UI is crashing.

**Comment by lwalter** [comment]
Very weird... I did as you said and it worked. I then tried enabling addons one at a time to see which was the culprit but eventually it worked despite all of them enabled. I'm unsure as to why I was seeing this behavior the other day. In any case we can close this as no repro.

I appreciate the help and the addon!
