### ISSUE TITLE
Bug with echo'ed skills

### ISSUE THREAD

**Issue by BrunoKrugel** [michaelnpsp/Grid2#99]
Grid2 v2.1.1

Evoker has the possibility of echo one spell, they have different spell ID but same name:

```
Reversion: 366155
Reversion Echo'd: 367364
```
When you add Reversion skill buff  (spell id 366155), it will track both of the skills (original and echo'ed), they will appear at the same place, with duration bug (because echo'ed spell have less duration).

If I choose the option to track by spell ID instead of the name, it will fix the duration bug, but, the addon will not let me add another Reversion (spell id 367364), because there is a nother buff with the same name already registered.

**Comment by michaelnpsp** [comment]
By default grid2 tracks spells by name, you have to create a second buff and enable the "track by spellid" option on both buffs.

You can create two buffs for the same name, you have two options.

 

Use a prefix to create the buff (valid prefixes separators: @#>), examples:

SecondReversion@367364

ReversionEchoed#367364

Evoker>367364

This is explained in the tooltip displayed when you put the mouse over the spellname editbox.

 

Another option is to write a different name for the status, type for example:

SecondReversion

and push create.

After this go to the new created buff configuration window.

The first option is a edit box displaying "SecondReversion", replace this name with the desired SpellID number and check the "track by SpellID" option.
